#!/usr/bin/env python
Import('env')

if env.get('WITH_MAKEMPS'):

	# To run the test, type
	#     ascdev test/dopri5/dopri5.a4c

	lib = env.SharedLibrary("makemps",["slv6.c","mps.c"]
		,LIBS = ['ascend']
		,LIBPATH = ['#']
		,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
		,SHLIBPREFIX = env['EXTLIB_PREFIX']		
	)

	env.Depends(lib,env['libascend'])

	env['extfns'] += lib

	if env.get('CAN_INSTALL'):
		dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
		env.InstallShared(dir,lib)

# vim: set syntax=python:
