Import('env')
dr_env = env.Copy()

srcs = Split("""
	datareader.c
	dr.c
	tmy.c
	texttable.c
	sun.c
""")

dr_env.Append(LIBPATH=['#'])
dr_env.Append(LIBS=['ascend'])
targets = []
targets.append( dr_env.SharedLibrary("datareader",srcs) )

env['extfns'] += targets

# vim: set syntax=python:

