Import('env')
dr_env = env.Clone()

srcs = Split("""
	datareader.c
	dr.c
	tmy.c
	csv.c
	acdb.c
	texttable.c
	sun.c
""")

dr_env.Append(LIBPATH=['#'])
dr_env.Append(LIBS=['ascend'])

lib = dr_env.SharedLibrary("datareader",srcs
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

env['extfns'] += [lib]

# vim: set syntax=python:

