#                        azeo_data.tcl
#                        by Robert S. Huss
#                        Part of the Ascend Library
#
#This file is part of the Ascend library.
#
#Copyright (C) 1994
#
#The Ascend library is free software; you can redistribute
#it and/or modify it under the terms of the GNU General Public License as
#published by the Free Software Foundation; either version 2 of the
#License, or (at your option) any later version.
#
#The Ascend Language Interpreter is distributed in hope that it will be
#useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#General Public License for more details.
#
#You should have received a copy of the GNU General Public License along with
#the program; if not, write to the Free Software Foundation, Inc., 675
#Mass Ave, Cambridge, MA 02139 USA.  Check the file named COPYING.

#  $Date: 1996/05/20 22:05:44 $
#  $Revision: 1.1.1.1 $
#  $Author: mthomas $
#  $Source: /afs/cs.cmu.edu/project/ascend/Repository/models/examples/flexible_design/azeo_data.tcl,v $


set azeo(acetone,benzene) none
set azeo(acetone,chloro_benzene) none
set azeo(acetone,chloroform) max
set azeo(acetone,diethylbenzene) none
set azeo(acetone,diphenyl) unconv
set azeo(acetone,ethanol) none
set azeo(acetone,ethylbenzene) none
set azeo(acetone,ethylene_glycol) none
set azeo(acetone,i_butane) none
set azeo(acetone,i_butanol) none
set azeo(acetone,i_pentane) min
set azeo(acetone,i_propanol) none
set azeo(acetone,methanol) min
set azeo(acetone,n_butane) none
set azeo(acetone,n_butanol) none
set azeo(acetone,n_decane) none
set azeo(acetone,n_heptane) min
set azeo(acetone,n_hexane) min
set azeo(acetone,n_octane) none
set azeo(acetone,n_pentane) min
set azeo(acetone,n_propanol) none
set azeo(acetone,pentanol_1) none
set azeo(acetone,propane) none
set azeo(acetone,propylene) none
set azeo(acetone,styrene) none
set azeo(acetone,toluene) none
set azeo(acetone,water) min
set azeo(benzene,acetone) none
set azeo(benzene,chloro_benzene) none
set azeo(benzene,chloroform) none
set azeo(benzene,diethylbenzene) none
set azeo(benzene,diphenyl) none
set azeo(benzene,ethanol) min
set azeo(benzene,ethylbenzene) none
set azeo(benzene,ethylene_glycol) none
set azeo(benzene,i_butane) none
set azeo(benzene,i_butanol) min
set azeo(benzene,i_pentane) none
set azeo(benzene,i_propanol) min
set azeo(benzene,methanol) min
set azeo(benzene,n_butane) none
set azeo(benzene,n_butanol) min
set azeo(benzene,n_decane) none
set azeo(benzene,n_heptane) min
set azeo(benzene,n_hexane) min
set azeo(benzene,n_octane) none
set azeo(benzene,n_pentane) none
set azeo(benzene,n_propanol) min
set azeo(benzene,pentanol_1) none
set azeo(benzene,propane) none
set azeo(benzene,propylene) none
set azeo(benzene,styrene) none
set azeo(benzene,toluene) none
set azeo(benzene,water) "min hetero"
set azeo(chloro_benzene,acetone) none
set azeo(chloro_benzene,benzene) none
set azeo(chloro_benzene,chloroform) none
set azeo(chloro_benzene,diethylbenzene) none
set azeo(chloro_benzene,diphenyl) none
set azeo(chloro_benzene,ethanol) none
set azeo(chloro_benzene,ethylbenzene) none
set azeo(chloro_benzene,ethylene_glycol) min
set azeo(chloro_benzene,i_butane) none
set azeo(chloro_benzene,i_butanol) min
set azeo(chloro_benzene,i_pentane) none
set azeo(chloro_benzene,i_propanol) none
set azeo(chloro_benzene,methanol) none
set azeo(chloro_benzene,n_butane) none
set azeo(chloro_benzene,n_butanol) min
set azeo(chloro_benzene,n_decane) none
set azeo(chloro_benzene,n_heptane) none
set azeo(chloro_benzene,n_hexane) none
set azeo(chloro_benzene,n_octane) min
set azeo(chloro_benzene,n_pentane) none
set azeo(chloro_benzene,n_propanol) min
set azeo(chloro_benzene,pentanol_1) min
set azeo(chloro_benzene,propane) unconv
set azeo(chloro_benzene,propylene) unconv
set azeo(chloro_benzene,styrene) none
set azeo(chloro_benzene,toluene) none
set azeo(chloro_benzene,water) "min hetero"
set azeo(chloroform,acetone) max
set azeo(chloroform,benzene) none
set azeo(chloroform,chloro_benzene) none
set azeo(chloroform,diethylbenzene) none
set azeo(chloroform,diphenyl) none
set azeo(chloroform,ethanol) min
set azeo(chloroform,ethylbenzene) none
set azeo(chloroform,ethylene_glycol) none
set azeo(chloroform,i_butane) none
set azeo(chloroform,i_butanol) none
set azeo(chloroform,i_pentane) none
set azeo(chloroform,i_propanol) min
set azeo(chloroform,methanol) min
set azeo(chloroform,n_butane) none
set azeo(chloroform,n_butanol) none
set azeo(chloroform,n_decane) none
set azeo(chloroform,n_heptane) none
set azeo(chloroform,n_hexane) min
set azeo(chloroform,n_octane) none
set azeo(chloroform,n_pentane) none
set azeo(chloroform,n_propanol) none
set azeo(chloroform,pentanol_1) none
set azeo(chloroform,propane) none
set azeo(chloroform,propylene) none
set azeo(chloroform,styrene) none
set azeo(chloroform,toluene) none
set azeo(chloroform,water) "min hetero"
set azeo(diethylbenzene,acetone) none
set azeo(diethylbenzene,benzene) none
set azeo(diethylbenzene,chloro_benzene) none
set azeo(diethylbenzene,chloroform) none
set azeo(diethylbenzene,diphenyl) none
set azeo(diethylbenzene,ethanol) none
set azeo(diethylbenzene,ethylbenzene) none
set azeo(diethylbenzene,ethylene_glycol) "min hetero"
set azeo(diethylbenzene,i_butane) unconv
set azeo(diethylbenzene,i_butanol) none
set azeo(diethylbenzene,i_pentane) none
set azeo(diethylbenzene,i_propanol) none
set azeo(diethylbenzene,methanol) none
set azeo(diethylbenzene,n_butane) unconv
set azeo(diethylbenzene,n_butanol) none
set azeo(diethylbenzene,n_decane) min
set azeo(diethylbenzene,n_heptane) none
set azeo(diethylbenzene,n_hexane) none
set azeo(diethylbenzene,n_octane) none
set azeo(diethylbenzene,n_pentane) none
set azeo(diethylbenzene,n_propanol) none
set azeo(diethylbenzene,pentanol_1) none
set azeo(diethylbenzene,propane) unconv
set azeo(diethylbenzene,propylene) unconv
set azeo(diethylbenzene,styrene) none
set azeo(diethylbenzene,toluene) none
set azeo(diethylbenzene,water) "min hetero"
set azeo(diphenyl,acetone) unconv
set azeo(diphenyl,benzene) none
set azeo(diphenyl,chloro_benzene) none
set azeo(diphenyl,chloroform) none
set azeo(diphenyl,diethylbenzene) none
set azeo(diphenyl,ethanol) unconv
set azeo(diphenyl,ethylbenzene) none
set azeo(diphenyl,ethylene_glycol) "min hetero"
set azeo(diphenyl,i_butane) unconv
set azeo(diphenyl,i_butanol) none
set azeo(diphenyl,i_pentane) unconv
set azeo(diphenyl,i_propanol) unconv
set azeo(diphenyl,methanol) unconv
set azeo(diphenyl,n_butane) unconv
set azeo(diphenyl,n_butanol) none
set azeo(diphenyl,n_decane) none
set azeo(diphenyl,n_heptane) none
set azeo(diphenyl,n_hexane) unconv
set azeo(diphenyl,n_octane) none
set azeo(diphenyl,n_pentane) unconv
set azeo(diphenyl,n_propanol) none
set azeo(diphenyl,pentanol_1) none
set azeo(diphenyl,propane) unconv
set azeo(diphenyl,propylene) unconv
set azeo(diphenyl,styrene) none
set azeo(diphenyl,toluene) none
set azeo(diphenyl,water) "min hetero"
set azeo(ethanol,acetone) none
set azeo(ethanol,benzene) min
set azeo(ethanol,chloro_benzene) none
set azeo(ethanol,chloroform) min
set azeo(ethanol,diethylbenzene) none
set azeo(ethanol,diphenyl) unconv
set azeo(ethanol,ethylbenzene) min
set azeo(ethanol,ethylene_glycol) none
set azeo(ethanol,i_butane) none
set azeo(ethanol,i_butanol) none
set azeo(ethanol,i_pentane) min
set azeo(ethanol,i_propanol) none
set azeo(ethanol,methanol) none
set azeo(ethanol,n_butane) none
set azeo(ethanol,n_butanol) none
set azeo(ethanol,n_decane) none
set azeo(ethanol,n_heptane) min
set azeo(ethanol,n_hexane) min
set azeo(ethanol,n_octane) min
set azeo(ethanol,n_pentane) min
set azeo(ethanol,n_propanol) none
set azeo(ethanol,pentanol_1) none
set azeo(ethanol,propane) none
set azeo(ethanol,propylene) none
set azeo(ethanol,styrene) min
set azeo(ethanol,toluene) min
set azeo(ethanol,water) min
set azeo(ethylbenzene,acetone) none
set azeo(ethylbenzene,benzene) none
set azeo(ethylbenzene,chloro_benzene) none
set azeo(ethylbenzene,chloroform) none
set azeo(ethylbenzene,diethylbenzene) none
set azeo(ethylbenzene,diphenyl) none
set azeo(ethylbenzene,ethanol) min
set azeo(ethylbenzene,ethylene_glycol) "min hetero"
set azeo(ethylbenzene,i_butane) unconv
set azeo(ethylbenzene,i_butanol) min
set azeo(ethylbenzene,i_pentane) none
set azeo(ethylbenzene,i_propanol) none
set azeo(ethylbenzene,methanol) min
set azeo(ethylbenzene,n_butane) none
set azeo(ethylbenzene,n_butanol) min
set azeo(ethylbenzene,n_decane) none
set azeo(ethylbenzene,n_heptane) none
set azeo(ethylbenzene,n_hexane) none
set azeo(ethylbenzene,n_octane) min
set azeo(ethylbenzene,n_pentane) none
set azeo(ethylbenzene,n_propanol) min
set azeo(ethylbenzene,pentanol_1) min
set azeo(ethylbenzene,propane) unconv
set azeo(ethylbenzene,propylene) unconv
set azeo(ethylbenzene,styrene) none
set azeo(ethylbenzene,toluene) none
set azeo(ethylbenzene,water) unconv
set azeo(ethylene_glycol,acetone) none
set azeo(ethylene_glycol,benzene) none
set azeo(ethylene_glycol,chloro_benzene) min
set azeo(ethylene_glycol,chloroform) none
set azeo(ethylene_glycol,diethylbenzene) "min hetero"
set azeo(ethylene_glycol,diphenyl) "min hetero"
set azeo(ethylene_glycol,ethanol) none
set azeo(ethylene_glycol,ethylbenzene) "min hetero"
set azeo(ethylene_glycol,i_butane) unconv
set azeo(ethylene_glycol,i_butanol) none
set azeo(ethylene_glycol,i_pentane) unconv
set azeo(ethylene_glycol,i_propanol) none
set azeo(ethylene_glycol,methanol) none
set azeo(ethylene_glycol,n_butane) unconv
set azeo(ethylene_glycol,n_butanol) none
set azeo(ethylene_glycol,n_decane) "min hetero"
set azeo(ethylene_glycol,n_heptane) "min hetero"
set azeo(ethylene_glycol,n_hexane) min
set azeo(ethylene_glycol,n_octane) "min hetero"
set azeo(ethylene_glycol,n_pentane) unconv
set azeo(ethylene_glycol,n_propanol) none
set azeo(ethylene_glycol,pentanol_1) none
set azeo(ethylene_glycol,propane) unconv
set azeo(ethylene_glycol,propylene) unconv
set azeo(ethylene_glycol,styrene) "min hetero"
set azeo(ethylene_glycol,toluene) min
set azeo(ethylene_glycol,water) none
set azeo(i_butane,acetone) none
set azeo(i_butane,benzene) none
set azeo(i_butane,chloro_benzene) none
set azeo(i_butane,chloroform) none
set azeo(i_butane,diethylbenzene) unconv
set azeo(i_butane,diphenyl) unconv
set azeo(i_butane,ethanol) none
set azeo(i_butane,ethylbenzene) unconv
set azeo(i_butane,ethylene_glycol) unconv
set azeo(i_butane,i_butanol) none
set azeo(i_butane,i_pentane) none
set azeo(i_butane,i_propanol) none
set azeo(i_butane,methanol) min
set azeo(i_butane,n_butane) none
set azeo(i_butane,n_butanol) none
set azeo(i_butane,n_decane) unconv
set azeo(i_butane,n_heptane) none
set azeo(i_butane,n_hexane) none
set azeo(i_butane,n_octane) none
set azeo(i_butane,n_pentane) none
set azeo(i_butane,n_propanol) none
set azeo(i_butane,pentanol_1) unconv
set azeo(i_butane,propane) none
set azeo(i_butane,propylene) none
set azeo(i_butane,styrene) unconv
set azeo(i_butane,toluene) none
set azeo(i_butane,water) unconv
set azeo(i_butanol,acetone) none
set azeo(i_butanol,benzene) min
set azeo(i_butanol,chloro_benzene) min
set azeo(i_butanol,chloroform) none
set azeo(i_butanol,diethylbenzene) none
set azeo(i_butanol,diphenyl) none
set azeo(i_butanol,ethanol) none
set azeo(i_butanol,ethylbenzene) min
set azeo(i_butanol,ethylene_glycol) none
set azeo(i_butanol,i_butane) none
set azeo(i_butanol,i_pentane) none
set azeo(i_butanol,i_propanol) none
set azeo(i_butanol,methanol) none
set azeo(i_butanol,n_butane) none
set azeo(i_butanol,n_butanol) none
set azeo(i_butanol,n_decane) none
set azeo(i_butanol,n_heptane) min
set azeo(i_butanol,n_hexane) min
set azeo(i_butanol,n_octane) min
set azeo(i_butanol,n_pentane) none
set azeo(i_butanol,n_propanol) none
set azeo(i_butanol,pentanol_1) none
set azeo(i_butanol,propane) unconv
set azeo(i_butanol,propylene) unconv
set azeo(i_butanol,styrene) min
set azeo(i_butanol,toluene) min
set azeo(i_butanol,water) min
set azeo(i_pentane,acetone) min
set azeo(i_pentane,benzene) none
set azeo(i_pentane,chloro_benzene) none
set azeo(i_pentane,chloroform) none
set azeo(i_pentane,diethylbenzene) none
set azeo(i_pentane,diphenyl) unconv
set azeo(i_pentane,ethanol) min
set azeo(i_pentane,ethylbenzene) none
set azeo(i_pentane,ethylene_glycol) unconv
set azeo(i_pentane,i_butane) none
set azeo(i_pentane,i_butanol) none
set azeo(i_pentane,i_propanol) min
set azeo(i_pentane,methanol) min
set azeo(i_pentane,n_butane) none
set azeo(i_pentane,n_butanol) none
set azeo(i_pentane,n_decane) none
set azeo(i_pentane,n_heptane) none
set azeo(i_pentane,n_hexane) none
set azeo(i_pentane,n_octane) none
set azeo(i_pentane,n_pentane) none
set azeo(i_pentane,n_propanol) none
set azeo(i_pentane,pentanol_1) none
set azeo(i_pentane,propane) none
set azeo(i_pentane,propylene) none
set azeo(i_pentane,styrene) none
set azeo(i_pentane,toluene) none
set azeo(i_pentane,water) "min hetero"
set azeo(i_propanol,acetone) none
set azeo(i_propanol,benzene) min
set azeo(i_propanol,chloro_benzene) none
set azeo(i_propanol,chloroform) min
set azeo(i_propanol,diethylbenzene) none
set azeo(i_propanol,diphenyl) unconv
set azeo(i_propanol,ethanol) none
set azeo(i_propanol,ethylbenzene) none
set azeo(i_propanol,ethylene_glycol) none
set azeo(i_propanol,i_butane) none
set azeo(i_propanol,i_butanol) none
set azeo(i_propanol,i_pentane) min
set azeo(i_propanol,methanol) none
set azeo(i_propanol,n_butane) none
set azeo(i_propanol,n_butanol) none
set azeo(i_propanol,n_decane) none
set azeo(i_propanol,n_heptane) min
set azeo(i_propanol,n_hexane) min
set azeo(i_propanol,n_octane) min
set azeo(i_propanol,n_pentane) min
set azeo(i_propanol,n_propanol) none
set azeo(i_propanol,pentanol_1) none
set azeo(i_propanol,propane) none
set azeo(i_propanol,propylene) none
set azeo(i_propanol,styrene) none
set azeo(i_propanol,toluene) min
set azeo(i_propanol,water) min
set azeo(methanol,acetone) min
set azeo(methanol,benzene) min
set azeo(methanol,chloro_benzene) none
set azeo(methanol,chloroform) min
set azeo(methanol,diethylbenzene) none
set azeo(methanol,diphenyl) unconv
set azeo(methanol,ethanol) none
set azeo(methanol,ethylbenzene) min
set azeo(methanol,ethylene_glycol) none
set azeo(methanol,i_butane) min
set azeo(methanol,i_butanol) none
set azeo(methanol,i_pentane) min
set azeo(methanol,i_propanol) none
set azeo(methanol,n_butane) min
set azeo(methanol,n_butanol) none
set azeo(methanol,n_decane) none
set azeo(methanol,n_heptane) min
set azeo(methanol,n_hexane) "min hetero"
set azeo(methanol,n_octane) min
set azeo(methanol,n_pentane) "min hetero"
set azeo(methanol,n_propanol) none
set azeo(methanol,pentanol_1) none
set azeo(methanol,propane) none
set azeo(methanol,propylene) none
set azeo(methanol,styrene) min
set azeo(methanol,toluene) min
set azeo(methanol,water) none
set azeo(n_butane,acetone) none
set azeo(n_butane,benzene) none
set azeo(n_butane,chloro_benzene) none
set azeo(n_butane,chloroform) none
set azeo(n_butane,diethylbenzene) unconv
set azeo(n_butane,diphenyl) unconv
set azeo(n_butane,ethanol) none
set azeo(n_butane,ethylbenzene) none
set azeo(n_butane,ethylene_glycol) unconv
set azeo(n_butane,i_butane) none
set azeo(n_butane,i_butanol) none
set azeo(n_butane,i_pentane) none
set azeo(n_butane,i_propanol) none
set azeo(n_butane,methanol) min
set azeo(n_butane,n_butanol) none
set azeo(n_butane,n_decane) unconv
set azeo(n_butane,n_heptane) none
set azeo(n_butane,n_hexane) none
set azeo(n_butane,n_octane) none
set azeo(n_butane,n_pentane) none
set azeo(n_butane,n_propanol) none
set azeo(n_butane,pentanol_1) none
set azeo(n_butane,propane) none
set azeo(n_butane,propylene) none
set azeo(n_butane,styrene) unconv
set azeo(n_butane,toluene) none
set azeo(n_butane,water) unconv
set azeo(n_butanol,acetone) none
set azeo(n_butanol,benzene) min
set azeo(n_butanol,chloro_benzene) min
set azeo(n_butanol,chloroform) none
set azeo(n_butanol,diethylbenzene) none
set azeo(n_butanol,diphenyl) none
set azeo(n_butanol,ethanol) none
set azeo(n_butanol,ethylbenzene) min
set azeo(n_butanol,ethylene_glycol) none
set azeo(n_butanol,i_butane) none
set azeo(n_butanol,i_butanol) none
set azeo(n_butanol,i_pentane) none
set azeo(n_butanol,i_propanol) none
set azeo(n_butanol,methanol) none
set azeo(n_butanol,n_butane) none
set azeo(n_butanol,n_decane) min
set azeo(n_butanol,n_heptane) min
set azeo(n_butanol,n_hexane) min
set azeo(n_butanol,n_octane) min
set azeo(n_butanol,n_pentane) none
set azeo(n_butanol,n_propanol) none
set azeo(n_butanol,pentanol_1) none
set azeo(n_butanol,propane) unconv
set azeo(n_butanol,propylene) unconv
set azeo(n_butanol,styrene) min
set azeo(n_butanol,toluene) min
set azeo(n_butanol,water) min
set azeo(n_decane,acetone) none
set azeo(n_decane,benzene) none
set azeo(n_decane,chloro_benzene) none
set azeo(n_decane,chloroform) none
set azeo(n_decane,diethylbenzene) min
set azeo(n_decane,diphenyl) none
set azeo(n_decane,ethanol) none
set azeo(n_decane,ethylbenzene) none
set azeo(n_decane,ethylene_glycol) "min hetero"
set azeo(n_decane,i_butane) unconv
set azeo(n_decane,i_butanol) none
set azeo(n_decane,i_pentane) none
set azeo(n_decane,i_propanol) none
set azeo(n_decane,methanol) none
set azeo(n_decane,n_butane) unconv
set azeo(n_decane,n_butanol) min
set azeo(n_decane,n_heptane) none
set azeo(n_decane,n_hexane) none
set azeo(n_decane,n_octane) none
set azeo(n_decane,n_pentane) none
set azeo(n_decane,n_propanol) none
set azeo(n_decane,pentanol_1) min
set azeo(n_decane,propane) unconv
set azeo(n_decane,propylene) unconv
set azeo(n_decane,styrene) min
set azeo(n_decane,toluene) none
set azeo(n_decane,water) unconv
set azeo(n_heptane,acetone) min
set azeo(n_heptane,benzene) min
set azeo(n_heptane,chloro_benzene) none
set azeo(n_heptane,chloroform) none
set azeo(n_heptane,diethylbenzene) none
set azeo(n_heptane,diphenyl) none
set azeo(n_heptane,ethanol) min
set azeo(n_heptane,ethylbenzene) none
set azeo(n_heptane,ethylene_glycol) "min hetero"
set azeo(n_heptane,i_butane) none
set azeo(n_heptane,i_butanol) min
set azeo(n_heptane,i_pentane) none
set azeo(n_heptane,i_propanol) min
set azeo(n_heptane,methanol) min
set azeo(n_heptane,n_butane) none
set azeo(n_heptane,n_butanol) min
set azeo(n_heptane,n_decane) none
set azeo(n_heptane,n_hexane) none
set azeo(n_heptane,n_octane) none
set azeo(n_heptane,n_pentane) none
set azeo(n_heptane,n_propanol) min
set azeo(n_heptane,pentanol_1) min
set azeo(n_heptane,propane) unconv
set azeo(n_heptane,propylene) unconv
set azeo(n_heptane,styrene) none
set azeo(n_heptane,toluene) min
set azeo(n_heptane,water) "min hetero"
set azeo(n_hexane,acetone) min
set azeo(n_hexane,benzene) min
set azeo(n_hexane,chloro_benzene) none
set azeo(n_hexane,chloroform) min
set azeo(n_hexane,diethylbenzene) none
set azeo(n_hexane,diphenyl) unconv
set azeo(n_hexane,ethanol) min
set azeo(n_hexane,ethylbenzene) none
set azeo(n_hexane,ethylene_glycol) min
set azeo(n_hexane,i_butane) none
set azeo(n_hexane,i_butanol) min
set azeo(n_hexane,i_pentane) none
set azeo(n_hexane,i_propanol) min
set azeo(n_hexane,methanol) "min hetero"
set azeo(n_hexane,n_butane) none
set azeo(n_hexane,n_butanol) min
set azeo(n_hexane,n_decane) none
set azeo(n_hexane,n_heptane) none
set azeo(n_hexane,n_octane) none
set azeo(n_hexane,n_pentane) none
set azeo(n_hexane,n_propanol) min
set azeo(n_hexane,pentanol_1) none
set azeo(n_hexane,propane) none
set azeo(n_hexane,propylene) none
set azeo(n_hexane,styrene) none
set azeo(n_hexane,toluene) none
set azeo(n_hexane,water) "min hetero"
set azeo(n_octane,acetone) none
set azeo(n_octane,benzene) none
set azeo(n_octane,chloro_benzene) min
set azeo(n_octane,chloroform) none
set azeo(n_octane,diethylbenzene) none
set azeo(n_octane,diphenyl) none
set azeo(n_octane,ethanol) min
set azeo(n_octane,ethylbenzene) min
set azeo(n_octane,ethylene_glycol) "min hetero"
set azeo(n_octane,i_butane) none
set azeo(n_octane,i_butanol) min
set azeo(n_octane,i_pentane) none
set azeo(n_octane,i_propanol) min
set azeo(n_octane,methanol) min
set azeo(n_octane,n_butane) none
set azeo(n_octane,n_butanol) min
set azeo(n_octane,n_decane) none
set azeo(n_octane,n_heptane) none
set azeo(n_octane,n_hexane) none
set azeo(n_octane,n_pentane) none
set azeo(n_octane,n_propanol) min
set azeo(n_octane,pentanol_1) min
set azeo(n_octane,propane) unconv
set azeo(n_octane,propylene) unconv
set azeo(n_octane,styrene) min
set azeo(n_octane,toluene) min
set azeo(n_octane,water) "min hetero"
set azeo(n_pentane,acetone) min
set azeo(n_pentane,benzene) none
set azeo(n_pentane,chloro_benzene) none
set azeo(n_pentane,chloroform) none
set azeo(n_pentane,diethylbenzene) none
set azeo(n_pentane,diphenyl) unconv
set azeo(n_pentane,ethanol) min
set azeo(n_pentane,ethylbenzene) none
set azeo(n_pentane,ethylene_glycol) unconv
set azeo(n_pentane,i_butane) none
set azeo(n_pentane,i_butanol) none
set azeo(n_pentane,i_pentane) none
set azeo(n_pentane,i_propanol) min
set azeo(n_pentane,methanol) "min hetero"
set azeo(n_pentane,n_butane) none
set azeo(n_pentane,n_butanol) none
set azeo(n_pentane,n_decane) none
set azeo(n_pentane,n_heptane) none
set azeo(n_pentane,n_hexane) none
set azeo(n_pentane,n_octane) none
set azeo(n_pentane,n_propanol) min
set azeo(n_pentane,pentanol_1) none
set azeo(n_pentane,propane) none
set azeo(n_pentane,propylene) none
set azeo(n_pentane,styrene) none
set azeo(n_pentane,toluene) none
set azeo(n_pentane,water) "min hetero"
set azeo(n_propanol,acetone) none
set azeo(n_propanol,benzene) min
set azeo(n_propanol,chloro_benzene) min
set azeo(n_propanol,chloroform) none
set azeo(n_propanol,diethylbenzene) none
set azeo(n_propanol,diphenyl) none
set azeo(n_propanol,ethanol) none
set azeo(n_propanol,ethylbenzene) min
set azeo(n_propanol,ethylene_glycol) none
set azeo(n_propanol,i_butane) none
set azeo(n_propanol,i_butanol) none
set azeo(n_propanol,i_pentane) none
set azeo(n_propanol,i_propanol) none
set azeo(n_propanol,methanol) none
set azeo(n_propanol,n_butane) none
set azeo(n_propanol,n_butanol) none
set azeo(n_propanol,n_decane) none
set azeo(n_propanol,n_heptane) min
set azeo(n_propanol,n_hexane) min
set azeo(n_propanol,n_octane) min
set azeo(n_propanol,n_pentane) min
set azeo(n_propanol,pentanol_1) none
set azeo(n_propanol,propane) unconv
set azeo(n_propanol,propylene) unconv
set azeo(n_propanol,styrene) min
set azeo(n_propanol,toluene) min
set azeo(n_propanol,water) min
set azeo(pentanol_1,acetone) none
set azeo(pentanol_1,benzene) none
set azeo(pentanol_1,chloro_benzene) min
set azeo(pentanol_1,chloroform) none
set azeo(pentanol_1,diethylbenzene) none
set azeo(pentanol_1,diphenyl) none
set azeo(pentanol_1,ethanol) none
set azeo(pentanol_1,ethylbenzene) min
set azeo(pentanol_1,ethylene_glycol) none
set azeo(pentanol_1,i_butane) unconv
set azeo(pentanol_1,i_butanol) none
set azeo(pentanol_1,i_pentane) none
set azeo(pentanol_1,i_propanol) none
set azeo(pentanol_1,methanol) none
set azeo(pentanol_1,n_butane) none
set azeo(pentanol_1,n_butanol) none
set azeo(pentanol_1,n_decane) min
set azeo(pentanol_1,n_heptane) min
set azeo(pentanol_1,n_hexane) none
set azeo(pentanol_1,n_octane) min
set azeo(pentanol_1,n_pentane) none
set azeo(pentanol_1,n_propanol) none
set azeo(pentanol_1,propane) unconv
set azeo(pentanol_1,propylene) unconv
set azeo(pentanol_1,styrene) min
set azeo(pentanol_1,toluene) min
set azeo(pentanol_1,water) "min hetero"
set azeo(propane,acetone) none
set azeo(propane,benzene) none
set azeo(propane,chloro_benzene) unconv
set azeo(propane,chloroform) none
set azeo(propane,diethylbenzene) unconv
set azeo(propane,diphenyl) unconv
set azeo(propane,ethanol) none
set azeo(propane,ethylbenzene) unconv
set azeo(propane,ethylene_glycol) unconv
set azeo(propane,i_butane) none
set azeo(propane,i_butanol) unconv
set azeo(propane,i_pentane) none
set azeo(propane,i_propanol) none
set azeo(propane,methanol) none
set azeo(propane,n_butane) none
set azeo(propane,n_butanol) unconv
set azeo(propane,n_decane) unconv
set azeo(propane,n_heptane) unconv
set azeo(propane,n_hexane) none
set azeo(propane,n_octane) unconv
set azeo(propane,n_pentane) none
set azeo(propane,n_propanol) unconv
set azeo(propane,pentanol_1) unconv
set azeo(propane,propylene) none
set azeo(propane,styrene) unconv
set azeo(propane,toluene) unconv
set azeo(propane,water) unconv
set azeo(propylene,acetone) none
set azeo(propylene,benzene) none
set azeo(propylene,chloro_benzene) unconv
set azeo(propylene,chloroform) none
set azeo(propylene,diethylbenzene) unconv
set azeo(propylene,diphenyl) unconv
set azeo(propylene,ethanol) none
set azeo(propylene,ethylbenzene) unconv
set azeo(propylene,ethylene_glycol) unconv
set azeo(propylene,i_butane) none
set azeo(propylene,i_butanol) unconv
set azeo(propylene,i_pentane) none
set azeo(propylene,i_propanol) none
set azeo(propylene,methanol) none
set azeo(propylene,n_butane) none
set azeo(propylene,n_butanol) unconv
set azeo(propylene,n_decane) unconv
set azeo(propylene,n_heptane) unconv
set azeo(propylene,n_hexane) none
set azeo(propylene,n_octane) unconv
set azeo(propylene,n_pentane) none
set azeo(propylene,n_propanol) unconv
set azeo(propylene,pentanol_1) unconv
set azeo(propylene,propane) none
set azeo(propylene,styrene) unconv
set azeo(propylene,toluene) unconv
set azeo(propylene,water) unconv
set azeo(styrene,acetone) none
set azeo(styrene,benzene) none
set azeo(styrene,chloro_benzene) none
set azeo(styrene,chloroform) none
set azeo(styrene,diethylbenzene) none
set azeo(styrene,diphenyl) none
set azeo(styrene,ethanol) min
set azeo(styrene,ethylbenzene) none
set azeo(styrene,ethylene_glycol) "min hetero"
set azeo(styrene,i_butane) unconv
set azeo(styrene,i_butanol) min
set azeo(styrene,i_pentane) none
set azeo(styrene,i_propanol) none
set azeo(styrene,methanol) min
set azeo(styrene,n_butane) unconv
set azeo(styrene,n_butanol) min
set azeo(styrene,n_decane) min
set azeo(styrene,n_heptane) none
set azeo(styrene,n_hexane) none
set azeo(styrene,n_octane) min
set azeo(styrene,n_pentane) none
set azeo(styrene,n_propanol) min
set azeo(styrene,pentanol_1) min
set azeo(styrene,propane) unconv
set azeo(styrene,propylene) unconv
set azeo(styrene,toluene) none
set azeo(styrene,water) unconv
set azeo(toluene,acetone) none
set azeo(toluene,benzene) none
set azeo(toluene,chloro_benzene) none
set azeo(toluene,chloroform) none
set azeo(toluene,diethylbenzene) none
set azeo(toluene,diphenyl) none
set azeo(toluene,ethanol) min
set azeo(toluene,ethylbenzene) none
set azeo(toluene,ethylene_glycol) min
set azeo(toluene,i_butane) none
set azeo(toluene,i_butanol) min
set azeo(toluene,i_pentane) none
set azeo(toluene,i_propanol) min
set azeo(toluene,methanol) min
set azeo(toluene,n_butane) none
set azeo(toluene,n_butanol) min
set azeo(toluene,n_decane) none
set azeo(toluene,n_heptane) min
set azeo(toluene,n_hexane) none
set azeo(toluene,n_octane) min
set azeo(toluene,n_pentane) none
set azeo(toluene,n_propanol) min
set azeo(toluene,pentanol_1) min
set azeo(toluene,propane) unconv
set azeo(toluene,propylene) unconv
set azeo(toluene,styrene) none
set azeo(toluene,water) "min hetero"
set azeo(water,acetone) min
set azeo(water,benzene) "min hetero"
set azeo(water,chloro_benzene) "min hetero"
set azeo(water,chloroform) "min hetero"
set azeo(water,diethylbenzene) "min hetero"
set azeo(water,diphenyl) "min hetero"
set azeo(water,ethanol) min
set azeo(water,ethylbenzene) unconv
set azeo(water,ethylene_glycol) none
set azeo(water,i_butane) unconv
set azeo(water,i_butanol) min
set azeo(water,i_pentane) "min hetero"
set azeo(water,i_propanol) min
set azeo(water,methanol) none
set azeo(water,n_butane) unconv
set azeo(water,n_butanol) min
set azeo(water,n_decane) unconv
set azeo(water,n_heptane) "min hetero"
set azeo(water,n_hexane) "min hetero"
set azeo(water,n_octane) "min hetero"
set azeo(water,n_pentane) "min hetero"
set azeo(water,n_propanol) min
set azeo(water,pentanol_1) "min hetero"
set azeo(water,propane) unconv
set azeo(water,propylene) unconv
set azeo(water,styrene) unconv
set azeo(water,toluene) "min hetero"
