Import('env')

print("PYTHON_PKG_EMBED =",env['PYTHON_PKG_EMBED'])

extfn_env = env.Clone()

srcs = Split("""
	extpy.c
""")

# get compile/link settings for libpython, Python.h
extfn_env.ParseConfig('pkg-config $PYTHON_PKG_EMBED --cflags --libs')
extfn_env.Append(LIBS=['ascend'],LIBPATH=['#'])

lib = extfn_env.SharedLibrary("extpy",srcs
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

# To run the test, type
#     ascdev johnpye/extpy/extpytest.py

# Return the targs
env['extfns'] += [lib]

# vim: set syntax=python:

