Import('env')
extfn_env = env.Copy()

srcs = Split("""
	extpy.c
""")

extfn_env.AppendUnique(
	LIBPATH=['#',env.get('PYTHON_LIBPATH')]	
	,LIBS=['ascend',env.get('PYTHON_LIB')]
	,CPPPATH=[env.get('PYTHON_CPPPATH')]
)

targets = []
targets.append( extfn_env.SharedLibrary("extpy",srcs) )

# To run the test, type
#     ascdev johnpye/extpy/extpytest.py

# Return the targs
env['extfns'] += targets

# vim: set syntax=python:

