Import('env')
extfn_env = env.Copy()

srcs = Split("""
	extpy.c
""")

extfn_env.Append(LIBPATH=['#'])
extfn_env.Append(LIBS=['ascend'])

targets = []
targets.append( extfn_env.SharedLibrary("extpy",srcs) )

# To run the test, type
#     ascdev johnpye/extpy/extpytest.py

# Return the targs
env['extfns'] += targets

# vim: set syntax=python:

