Import('env')
brent_env = env.Copy()

srcs = Split("""
	brent.c
""")

brent_env.Append(LIBPATH=['#'])
brent_env.Append(LIBS=['ascend'])

lib = brent_env.SharedLibrary("brent",srcs
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

env['extfns'] += [lib]

# vim: set syntax=python:
