Import('env')

solver_env = env.Copy()

if solver_env.get('WITH_CONOPT'):
	solver_env.AppendUnique(CPPPATH=[solver_env.get('CONOPT_CPPPATH')])

env['extfns'] += [solver_env.SharedLibrary("cmslv",["slv9.c"]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
)]

# vim: set syntax=python:

