Import('env')

solver_env = env.Copy()

srcs = ['lsode.f','lsode.c']

lsode = solver_env.SharedObject('lsode')

#if 'LSOD' in solver_env.get('WITH_SOLVERS'):

if env.get('F2C_LIBPATH'):
	solver_env.AppendUnique(LIBPATH=[env.get('F2C_LIBPATH')])

if solver_env.get('F2C_LIB'):
	solver_env.AppendUnique(LIBS=[env.get('F2C_LIB')])

liblsode = solver_env.SharedLibrary('lsode',srcs)

env['extfns'] += [liblsode]

# vim: set syntax=python:
