Import('env')

srcs = Split("""
	redirectStdStreams.c
	printutil.c
	assertimpl.c
""")

test_cpppath = [
	'#base/generic'
	, '#test'
]
if env.has_key('CUNIT_CPPPATH'):
	test_cpppath.append(env['CUNIT_CPPPATH'])

env.Library('asctest',srcs
	, CPPPATH=test_cpppath
)
