#!/bin/bash
cd $(dirname "$0")
cd ..
export LD_LIBRARY_PATH=$HOME/.local/lib:.
export ASCENDLIBRARY=models
export ASCENDSOLVERS=solvers/ipopt:solvers/qrslv:solvers/lrslv:solvers/dopri5:solvers/ida:solvers/radau5:solvers/ipslv:solvers/cmslv:solvers/conopt

test/test -r expectpass

# CURRENTLY FAILING IN MSYS2:

# general_tm_time
# integrator_lsode
# QUESTIONABLE: compiler_bintok (error writing /tmp/btsrc.c...)

# CURRENTLY FAILING independent of issues with memory leakage:

# solver_ipopt 
# solver_conopt 
# solver_qrslv 
# compiler_autodiff
# compiler_blackbox
# system_link 
# integrator_ida

# TESTS REQUIRING MALLOC_DEBUG:
# general_hashpjw 
# general_list
# general_pool
# general_stack general_table 
# general_ascMalloc
# utilities_set 
# solver_slv_common
