#!/bin/bash
cd $(dirname "$0")
cd ..
export LD_LIBRARY_PATH=$HOME/.local/lib:.
export ASCENDLIBRARY=models
export ASCENDSOLVERS=solvers/ipopt:solvers/qrslv:solvers/lrslv:solvers/dopri5:solvers/ida:solvers/radau5:solvers/ipslv:solvers/cmslv:solvers/conopt

test/test general_color general_dstring general_listio general_pretty general_tm_time general_ospath general_env general_ltmatrix utilities_ascDynaLoad utilities_ascEnvVar utilities_ascPrint utilities_ascSignal utilities_readln linear_qrrank linear_mtx compiler_basics compiler_expr compiler_fixfree compiler_fixassign compiler_instantiate_set_enum compiler_instantiate_relation_logrel_bool compiler_instantiate_logrel_bool_algebra compiler_instantiate_array compiler_instantiate_for compiler_instantiate_alike compiler_instantiate_context compiler_instantiate_anontype solver_slvreq integrator_lsode solver_fprops solver_lrslv compiler_bintok

# CURRENTLY FAILING IN MSYS2:

# general_tm_time
# integrator_lsode
# QUESTIONABLE: compiler_bintok (error writing /tmp/btsrc.c...)

# CURRENTLY FAILING independent of issues with memory leakage:

# solver_ipopt 
# solver_conopt 
# solver_qrslv 
# compiler_autodiff
# compiler_blackbox
# system_link 
# integrator_ida

# TESTS REQUIRING MALLOC_DEBUG:
# general_hashpjw 
# general_list
# general_pool
# general_stack general_table 
# general_ascMalloc
# utilities_set 
# solver_slv_common
