#!/bin/bash
cd $(dirname "$0")
cd ..
export LD_LIBRARY_PATH=.:~/.local/lib:/usr/local/lib
export ASCENDLIBRARY=models
export ASCENDSOLVERS=solvers/ipopt:solvers/qrslv:solvers/lrslv:solvers/dopri5:solvers/ida:solvers/radau5:solvers/ipslv:solvers/cmslv:solvers/conopt
test/test general_color general_dstring general_hashpjw general_list general_pairlist general_listio general_mem general_pool general_pretty general_stack general_table general_tm_time general_ospath general_env general_ltmatrix general_ascMalloc utilities_error utilities_ascDynaLoad utilities_ascEnvVar utilities_ascPrint utilities_ascSignal utilities_readln utilities_set solver_slv_common solver_slvreq linear_mtx compiler_basics compiler_func compiler_units compiler_expr compiler_relation compiler_fixfree compiler_chkdim compiler_dimen compiler_fractions compiler_name compiler_symtab compiler_fixassign compiler_qlfdid compiler_autodiff compiler_bintok packages_defaultall solver_lrslv solver_ipopt integrator_lsode

# currently failing tests:
# solver_conopt solver_qrslv 
# compiler_blackbox system_link 
# integrator_ida

# tests that pass but with memory leaks:
# 
# solver_fprops
# linear_qrrank

# suppressed for other reasons:
# compiler_qlfdid (didn't have PCRE enabled atm)

