#!/bin/sh

if [ "x$ASCENDLIBRARY" != "x" ]; then
    echo "USING ASCENDLIBRARY=$ASCENDLIBRARY"
fi

args=$@

if [ "$OSTYPE" = "cygwin" ]; then
    echo "CYGWIN..."
elif [ "$OSTYPE" = "msys" ]; then
    #echo "MSYS..."
    PYTHON=/c/Python24/python
fi

if [ $PYTHON ]; then 
    python=$PYTHON
else
    python=python
fi


if [ $ASCEND_GDB ]; then
    bin="gdb --args $python" 
else
    bin=$python
fi

if [ "x$ASC_DEVELOPING" != "x" ]; then
	# set the 'ASC_DEVELOPING' environment variable
	# if you don't want to run ASCEND from the installed location
	cmd="$bin gtkbrowser.py --pygtk-assets=glade/ $args"
else
	cmd="$bin /home/john/share/ascend/gtkbrowser.py $args"
fi

$cmd

