#!/bin/sh

if [ "x$ASCENDLIBRARY" = "x" ]; then
	echo "USING ASCENDLIBRARY=$ASCENDLIBRARY"
fi

args=$@

if [ "$OSTYPE" = "cygwin" ]; then
    echo "CYGWIN..."
elif [ "$OSTYPE" = "msys" ]; then
    echo "MSYS..."
    PYTHON=/c/Python24/python
fi

if [ $PYTHON ]; then 
    python=$PYTHON
else
    python=python
fi


if [ $ASCEND_GDB ]; then
    bin="gdb --args $python" 
else
    bin=$python
fi

dir=`dirname $0`
cmd="$bin $dir/gtkbrowser.py $args"

$cmd

