#!/bin/bash
export ASCENDLIBRARY=~/ascdata:~/src/ascend/trunk/models

args=$@

if [ "$OSTYPE" = "cygwin" ]; then
    echo "CYGWIN..."
fi

if [ $ASCEND_GDB ]; then
	bin="gdb --args python" 
elif [ $PYTHON ]; then
    bin=$PYTHON
else
	bin=python
fi

dir=`dirname $0`
cmd="$bin $dir/gtkbrowser.py $args"

$cmd

