Import('env')

srcs = Split("""

	library.cpp type.cpp module.cpp symchar.cpp
	instance.cpp instanceinterfacedata.cpp
	method.cpp name.cpp
	reporter.cpp simulation.cpp set.cpp units.cpp dimensions.cpp extmethod.cpp
	variable.cpp relation.cpp
	solver.cpp curve.cpp plot.cpp
	solverparameters.cpp solverparameter.cpp solverparameteriterator.cpp
	solverstatus.cpp solverreporter.cpp
	incidencematrix.cpp

""")

libs = Split("""
	asccompiler ascpackages ascsolver ascutilities ascgeneral 
""")

swig = CFile(target=['ascend_wrap.cc'],source=['ascend.i']
	, SWIGFLAGS=['-python','-c++']
)
env.Depends('ascend.py',swig);

libpath = [
	'../../base/generic/compiler'
	,'../../base/generic/packages'
	,'../../base/generic/solver'
	,'../../base/generic/utilities'
	,'../../base/generic/general'
]

lib = env.SharedLibrary("ascend",srcs+swig
	, LIBS = libs #+env['PYTHON_LIB']
	, LIBPATH = libpath+env['PYTHON_LIBPATH']
	, CPPPATH = ['../../base/generic']+env['PYTHON_CPPPATH']
	, CPPDEFINES = ['ASCXX_USE_PYTHON']
	, SHLIBPREFIX = '_'
)

env.Depends(lib,'ascend.py')
