Import('env')
extenv = env.Clone()

subdirs = [
	'qrslv','conopt','cmslv','lrslv','lsode','ida','ipopt','dopri5'
]
#'tron',

for d in subdirs:
	extenv.SConscript(d+'/SConscript',['env']);

# vim: set syntax=python:
