Import('env')
extenv = env.Copy()

subdirs = [
	'qrslv','conopt','cmslv','lrslv','tron'
]

for d in subdirs:
	extenv.SConscript(d+'/SConscript',['env']);

Return('subdirs')

# vim: set syntax=python:
