/*	ASCEND modelling environment
	Copyright (C) 2008 Carnegie Mellon University

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2, or (at your option)
	any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place - Suite 330,
	Boston, MA 02111-1307, USA.
*/

#include "carbondioxide.h"

#define CARBONDIOXIDE_R 188.9241
#define CARBONDIOXIDE_TSTAR 304.1282
#define CARBONDIOXIDE_M 44.0098
#define CARBONDIOXIDE_PC 73773e6
#define CARBONDIOXIDE_RHOC 467.6

/**
	Ideal gas data for CO2
*/
const IdealData ideal_data_carbondioxide = {
	0 /* constant */
	, 0 /* linear */
	, CARBONDIOXIDE_TSTAR /* Tstar / [K] */
	, CARBONDIOXIDE_R /* cpstar / [J/kgK] */
	, 2
	, (const IdealPowTerm*){
		{18.37304456, 0}
		,{-3.70454304, 1}
	}
	, 5
	, (const IdealExpTerm[]){
		{1.99427042, 3.15163}
		,{0.62105248, 6.11190}
		,{0.41195293, 6.77708}
		,{1.04028922, 11.32384}
		,{0.08327678, 27.08792}
	}
};

/**
	Residual (non-ideal) property data for ,....
*/
const HelmholtzData helmholtz_data_carbondioxide = {
	/* R */ CARBONDIOXIDE_R /* 1000 * kJ/kmolK / kg/kmol = J/kgK */
	, /* M */ CARBONDIOXIDE_M /* kg/kmol */
	, /* rho_star */ CARBONDIOXIDE_RHOC /* kg/m³ (= rho_c for this model) */
	, /* T_star */ CARBONDIOXIDE_TSTAR /* K (= T_c for this model) */
	, ????? /* acentric factor, from Reid, Prausnitz & Polling */
	, &ideal_data_carbondioxide
	, ???? /* power terms */
	, (const HelmholtzPowTerm[]){
		/* a_i, t_i, d_i, l_i */
		{-0.693643e1,  0.6844,   1.0,  0.0}
		, {0.01,         1.,    4.0,  0.0}
		, {2.1101,      0.989,    1.0,  0.0}
			, {4.52059,  0.489,    1.0,  0.0}
		, {0.732564,  0.803,    2.0,  0.0}
		, {-1.34086,  1.1444,   2.0,  0.0}
		, {0.130985,  1.409,    3.0,  0.0}
		, {-0.777414,  1.754,    1.0,  1.0}
		, {0.351944,  1.311,    3.0 , 1.0}
	}
	, 5 /* critical (gaussian) terms */
 	, (const HelmholtzGausTerm[]){
		/* a, t, d, alpha, beta, gamma, epsilon */
		{-0.211716e-1, 4.187,   2.0, 1.685, 0.1710, 0.7164, 1.506}
		, {0.226312e-1, 5.646,  1.0, 0.489, 0.2245, 1.3444, 0.156}
		, {0.321870e-1, 0.791,  3.0, 0.103, 0.1304, 1.4517, 1.736}
		, {-0.231752e-1,  7.249,1.0, 2.506, 0.2785, 0.7204, 0.670}
		, {0.557346e-1,  2.986, 1.0, 1.607, 0.3967, 1.5445, 1.662}
	}
	, 0 /* nc2 */, 0
};

/*
	Test suite. These tests attempt to validate the current code using 
	a few sample figures output by REFPROP 7.0.

	To run the test, compile and run as follows:

	gcc ideal.c helmholtz.c carbondioxide.c -DTEST -o carbondioxide -lm && ./carbondioxide 

	These tests all currently pass with a maximum error of 0.09%.
*/
#ifdef TEST

#include <assert.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

typedef struct{double T,p,rho,u,h,s,cv,cp,cp0,a;} TestData;
const TestData td[]; const unsigned ntd;

int main(void){
	unsigned n, i;
	double rho, T, cp0, p, u, h, a, s;
	const HelmholtzData *d;

	d = &helmholtz_data_carbondioxide;
	double maxerr = 0;

	n = ntd;
	fprintf(stderr,"Running through %d test points...\n",n);

/* a simple macro to actually do the testing */
#define ASSERT_TOL(FN,PARAM1,PARAM2,PARAM3,VAL,TOL) {\
		double cval; cval = FN(PARAM1,PARAM2,PARAM3);\
		double err; err = cval - (double)(VAL);\
		double relerrpc = (cval-(VAL))/(VAL)*100;\
		if(fabs(relerrpc)>maxerr)maxerr=fabs(relerrpc);\
		if(fabs(err)>fabs(TOL)){\
			fprintf(stderr,"ERROR in line %d: value of '%s(%f,%f,%s)' = %0.8f,"\
				" should be %f, error is %.10e (%.2f%%)!\n"\
				, __LINE__, #FN,PARAM1,PARAM2,#PARAM3, cval, VAL,cval-(VAL)\
				,relerrpc\
			);\
			exit(1);\
		}else{\
			fprintf(stderr,"    OK, %s(%f,%f,%s) = %8.2e with %.6f%% err.\n"\
				,#FN,PARAM1,PARAM2,#PARAM3,VAL,relerrpc\
			);\
		}\
	}

#define CP0(T,RHO,DATA) helmholtz_cp0(T,DATA)

	fprintf(stderr,"CP0 TESTS\n");
	for(i=0; i<n;++i){
		cp0 = td[i].cp0*1e3;
	 	ASSERT_TOL(CP0, td[i].T+273.15, 0., d, cp0, cp0*1e-1);
	}
#undef CP0

	fprintf(stderr,"Tests completed OK (maximum error = %0.2f%%)\n",maxerr);
	exit(0);
}

/*
	Some test data generated by REFPROP 7.0 for p=0.1, 1, 10, 20, 100 MPa.
*/
const TestData td[] = {
/*{T/C,   , p/MPa  , rho/(kg/m3)   , u/(kJ/kg)     , h/(kJ/kg)     , s/(kJ/kgK)    , cv/(kJ/kgK)   , cp(kJ/kgK)    , cp0/(kJ/kgK)    a/(kJ/kg)}*/

};

const unsigned ntd = sizeof(td)/sizeof(TestData);

#endif
