Import('env')
fprops_env = env.Clone()

fprops_env.Append(LIBPATH=['#'])
fprops_env.Append(LIBS=['ascend'])

lib = fprops_env.SharedLibrary("mbwr"
	,['mbwr.c','asc_mbwr.c']
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)


lib = fprops_env.SharedLibrary("helmholtz"
	,['helmholtz.c','asc_helmholtz.c','ammonia.c']
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

env['extfns'] += [lib]

# vim: set syntax=python:

