Import('fprops_env')
import os

pyenv = fprops_env.Clone()
pyenv.ParseConfig('pkg-config $PYTHON_PKG --cflags --libs')

if 0:
	pyenv['LIBS'] = []
	pyenv['SHLIBSUFFIX'] = '.so'
	pyenv['SHLIBPREFIX'] = '_'

	import distutils.sysconfig, sys, platform

	if platform.system()=="Windows":
		python_lib='python%d%d'
		pyenv['SHLIBSUFFIX']='.pyd'
	else:
		python_lib='python%d.%d'

	if not fprops_env.get('PYTHON_LIBPATH'):
		cfig = distutils.sysconfig.get_config_vars()
		python_libpath = []
		python_linkflags = []
		if platform.system()=="Windows":
			python_libpath += [os.path.join(sys.prefix,"libs")]
		elif platform.system()=="Darwin":
			python_libpath += [cfig['LIBPL']]
			python_linkflags += cfig['LIBS'].split(' ')
		else:
			# checked on Linux and SunOS
			if cfig['LDLIBRARY']==cfig['LIBRARY']:
				sys.stdout.write("(static)")
				python_libpath += [cfig['LIBPL']]
				python_linkflags += cfig['LIBS'].split(' ')
		fprops_env['PYTHON_LIBPATH'] = python_libpath

lib = pyenv.SharedLibrary('fprops',['fprops.i'] + fprops_env['shobjs']
#	,LIBPATH=['..']
#	,CPPPATH=['#']
#	,LIBS=["m"]
	,SWIGFLAGS=['-python']
)

pyenv.Depends(lib,"fprops_wrap.c")
#pyenv.Depends(lib,fprops_env['libfprops'])

fprops_env['pyfprops'] = lib

