Import('env')

# To run the test, type
#     ascend johnpye/qrslv/qrslv.a4c

libqrslv = [env.SharedLibrary("qrslv",["qrslv.c"]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
)]

env['extfns'] += libqrslv

if env.get('CAN_INSTALL'):
	dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
	env.InstallShared(dir,libqrslv)

# vim: set syntax=python:
