Import('env')
qrslv_env = env.Clone()

lib = qrslv_env.SharedLibrary("qrslv",["qrslv.c"]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

env['extfns'] += [lib]

env.Depends(lib,env['libascend'])

if env.get('CAN_INSTALL'):
	dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
	env.InstallShared(dir,lib)

# vim: set syntax=python:
