Import('env')

# To run the test, type
#     ascend johnpye/qrslv/qrslv.a4c

lib = env.SharedLibrary("qrslv",["qrslv.c"]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

env['extfns'] += [lib]

env.Depends(lib,env['libascend'])

if env.get('CAN_INSTALL'):
	dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
	env.InstallShared(dir,lib)

# vim: set syntax=python:
