# :vim: set syntax=python:

 
print "SCONS not yet set up here. Try the following..."
print "lyx -e latex book.lyx"
print "then"
print "latex2html --show_section_numbers --html_version=4.0 book.tex"

print "or"
print "pdflatex book.tex"
