Import('env')
extfn_env = env.Copy()

srcs = Split("""
	bboxtest.c
""")

extfn_env.Append(
	LIBPATH=['#']
	,LIBS=['ascend']
)

lib = extfn_env.SharedLibrary("bboxtest",srcs
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

# Return the targs
env['extfns'] += [lib]

# vim: set syntax=python:

