Import('env')
extfn_env = env.Copy()

srcs = Split("""
	bboxtest.c
""")

extfn_env.Append(LIBPATH=['#'])
extfn_env.Append(LIBS=['ascend'])

targets = []
targets.append( extfn_env.SharedLibrary("bboxtest",srcs) )

# Return the targs
env['extfns'] += targets

# vim: set syntax=python:

