Import('env')

# To run the test, type
#     ascend johnpye/qrslv/qrslv.a4c

qrslvobj = env.SharedObject("qrslv.c")

if 1:
	env['extfns'] += [env.SharedLibrary("qrslv",[qrslvobj]
		,LIBS = ['ascend']
		,LIBPATH = ['#']
	)]

# vim: set syntax=python:

