Import('env')

solver_env = env.Copy()

if solver_env.get('WITH_TRON'):
	solver_env.AppendUnique(CPPPATH=[solver_env.get('TRON_CPPPATH')])

lib = solver_env.SharedLibrary("tron",["asc_tron.c"]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

env.Depends(lib,env['libascend'])

env['extfns'] += [lib]

# vim: set syntax=python:
