
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE typ_restart(typ_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int typ_leng;

extern FILE *typ_in, *typ_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE typ_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-typ_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < typ_leng; ++yyl )\
                    if ( typ_text[yyl] == '\n' )\
                        --typ_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up typ_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up typ_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via typ_restart()), so that the user can continue scanning by
	 * just pointing typ_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when typ_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int typ_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow typ_wrap()'s to do buffer switches
 * instead of setting up a fresh typ_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void typ_restart (FILE *input_file  );
void typ__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE typ__create_buffer (FILE *file,int size  );
void typ__delete_buffer (YY_BUFFER_STATE b  );
void typ__flush_buffer (YY_BUFFER_STATE b  );
void typ_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void typ_pop_buffer_state (void );

static void typ_ensure_buffer_stack (void );
static void typ__load_buffer_state (void );
static void typ__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER typ__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE typ__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE typ__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE typ__scan_bytes (yyconst char *bytes,int len  );

void *typ_alloc (yy_size_t  );
void *typ_realloc (void *,yy_size_t  );
void typ_free (void *  );

#define yy_new_buffer typ__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        typ_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            typ__create_buffer(typ_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        typ_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            typ__create_buffer(typ_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *typ_in = (FILE *) 0, *typ_out = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int typ_lineno;

int typ_lineno = 1;

extern char typ_text[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up typ_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	typ_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( typ_leng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &typ_text[(yy_more_offset)], (yytext_ptr), typ_leng + 1 ); \
	typ_leng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[156] =
    {   0,
        6,    6,   16,   16,   35,   31,   34,   32,   34,   33,
       34,   33,   34,   33,   34,   33,   34,   33,   34,   33,
       34,   31,   33,   34,    9,   34,    6,   34,    7,   34,
        8,   34,   16,   34,   34,   14,   34,   15,   34,   20,
       34,   21,   34,   22,   34,   22,   34,   20,   22,   34,
       10,   34,   24,   34,   25,   34,   23,   34,   11,   34,
       18,   34,   34,   17,   18,   34,   31,   32,   32,    1,
       33,   33,   33,   33,   33,   33,   33,   33,   31,   33,
       31,   33,   31,   33,    6,    7,    7,    4,    8,    5,
        8,   16,   15,   12,   13,   14,   20,   21,   21,    2,

       22,   22,   22,   22,   20,   22,   20,   22,   20,   22,
       24,   25,   25,    3,   17,   33,   33,   33,   33,   33,
        4,   22,   33,   33,   33,   33,   33,   19,   22,   28,
       33,   33,   33,   33,   33,   33,   33,   27,   33,   33,
       33,   33,   33,   33,   33,   33,   30,   33,   33,   33,
       33,   26,   33,   29,   33
    } ;

static yyconst flex_int16_t yy_accept[125] =
    {   0,
        1,    1,    1,    2,    3,    4,    5,    5,    5,    5,
        5,    5,    5,    6,    8,   10,   12,   14,   16,   18,
       20,   22,   25,   27,   29,   31,   33,   35,   36,   38,
       40,   42,   44,   46,   48,   51,   53,   55,   57,   59,
       61,   63,   64,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   76,   77,   78,   79,   81,   83,   85,   86,
       86,   87,   88,   89,   90,   91,   92,   93,   93,   94,
       95,   96,   97,   98,   99,  100,  101,  102,  103,  104,
      105,  107,  109,  111,  112,  113,  114,  115,  116,  117,
      118,  119,  120,  121,  122,  123,  124,  125,  126,  127,

      128,  130,  132,  133,  134,  135,  136,  137,  138,  140,
      141,  142,  143,  144,  145,  146,  147,  149,  150,  151,
      152,  154,  156,  156
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    6,    1,    1,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    8,    1,
        1,    1,    1,    1,    9,   10,   11,   12,   13,   14,
       10,   10,   15,   10,   10,   16,   17,   18,   19,   10,
       10,   20,   21,   22,   23,   24,   10,   10,   10,   10,
        1,   25,    1,    1,   26,    1,   27,   27,   27,   27,

       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   28,    1,   29,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[30] =
    {   0,
        1,    2,    1,    3,    1,    4,    5,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    8,    9,    5,   10,    8
    } ;

static yyconst flex_int16_t yy_base[143] =
    {   0,
        0,    0,   26,   27,    9,   11,   40,    0,   66,   67,
       95,    0,  343,    0,   72,   71,   75,  123,   78,  124,
      126,  144,  467,  333,   78,   82,   56,  327,    0,  467,
        0,   86,  125,  146,  173,  467,    0,  131,  467,  467,
      467,  467,    0,    0,  132,  322,  467,  289,  287,  151,
      153,  175,  154,  155,  180,  286,  285,    0,  280,  124,
      135,  154,    0,  160,  467,  179,  161,  277,  467,  467,
      467,    0,    0,  183,  264,  467,  261,  256,  189,  199,
      254,  229,    0,    0,  188,  199,  467,    0,  202,  204,
      206,  207,  214,    0,  215,  216,  224,  225,  226,  227,

      211,  194,  228,  237,  239,  242,  246,  247,  138,  249,
      251,  259,  263,  258,  273,  274,   87,  275,  276,  277,
       70,   33,  467,  293,  303,  313,  323,  332,  340,  349,
      359,  369,  379,  388,  398,  407,  416,  424,  433,  442,
      447,  456
    } ;

static yyconst flex_int16_t yy_def[143] =
    {   0,
      123,    1,  124,  124,  125,  125,  123,    7,  126,  126,
      123,   11,  123,  127,  128,  129,  129,  129,  129,  129,
      129,  129,  123,  130,  131,  132,  133,  134,  135,  123,
      136,  137,  138,  138,  138,  123,  139,  140,  123,  123,
      123,  123,  141,  127,  128,   45,  123,  123,  123,  129,
      129,  129,  129,  129,  129,  127,  127,   22,  130,  123,
      131,  131,  142,  132,  123,  132,  133,  134,  123,  123,
      123,  135,  136,  137,   74,  123,  123,  123,  138,  138,
      136,  136,   35,  139,  140,  140,  123,  141,  129,  129,
      129,  129,  129,  142,  138,  129,  129,  129,  129,  129,

      123,  123,  129,  129,  129,  129,  129,  129,  123,  129,
      129,  129,  129,  129,  129,  129,  123,  129,  129,  129,
      123,  123,    0,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123
    } ;

static yyconst flex_int16_t yy_nxt[497] =
    {   0,
       14,   14,   14,   15,   14,   14,   14,   14,   16,   17,
       18,   19,   17,   17,   17,   17,   20,   17,   17,   17,
       17,   17,   21,   17,   14,   22,   14,   23,   14,   25,
       25,   26,   26,   28,  122,   28,   29,   30,   29,   30,
       31,   31,   31,   32,   31,   31,   31,   31,   33,   33,
       33,   33,   34,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   31,   35,   31,   36,   31,   38,
       38,  121,   48,   39,   39,   46,   48,   47,   49,   48,
       68,   62,   49,   63,   69,   49,   65,   66,  117,   75,
       53,   76,   51,   40,   40,   41,   41,   42,   41,   41,

       41,   41,   41,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   41,
       41,   43,   41,   41,   48,   48,   77,   48,   65,   60,
       49,   49,   78,   49,   86,  123,   87,  123,  123,  109,
      123,   52,   54,   55,   44,   56,   44,   77,   44,   44,
       44,   57,   48,   78,   48,   48,   48,   62,   49,  123,
       49,   49,   49,   80,  123,  123,   92,   91,   44,   58,
       44,   89,   44,   73,   81,   73,   48,   73,   73,   73,
       82,   48,   49,   65,   66,   68,  123,   49,  123,   69,
       77,  123,   90,  123,   93,  102,   78,   73,   83,   73,

       77,   73,   86,   48,  123,   48,   78,   48,   48,   49,
       95,   49,  101,   49,   49,   48,  101,  102,   96,   99,
       98,   49,   78,   49,   97,   48,   48,   48,   48,   48,
       81,   49,   49,   49,   49,   49,  107,  100,   48,  106,
      109,  105,  104,   48,   49,  103,   49,   48,   48,   49,
       48,  108,   48,   49,   49,   81,   49,   77,   49,  117,
       48,  110,   77,  111,   48,   49,   49,   75,  112,  113,
       49,  116,  114,  115,   48,   48,   48,  121,  122,   71,
       49,   49,   49,   49,   49,   60,   56,   56,   48,  119,
       48,  118,  120,   24,   24,   24,   24,   24,   24,   24,

       24,   24,   24,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   44,   44,   46,   44,   44,   44,   71,
       44,   44,   45,   45,   45,   45,   45,   45,   60,   45,
       45,   50,  123,  123,  123,   50,   50,  123,   50,   59,
       59,  123,   59,   59,   59,   59,   59,   59,   59,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   64,
       64,  123,   64,   64,   64,   64,   64,   64,   64,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   72,   72,

       72,   72,   72,   72,   72,  123,   72,   73,   73,  123,
       73,   73,   73,  123,   73,   73,   74,   74,   74,   74,
       74,   74,  123,   74,   74,   79,  123,  123,  123,   79,
       79,  123,   79,   84,   84,  123,   84,   84,  123,   84,
       84,   84,   85,   85,   85,   85,   85,  123,   85,   85,
       85,   88,  123,   88,  123,   88,   94,   94,  123,  123,
       94,   94,   94,   94,   94,   94,   13,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123

    } ;

static yyconst flex_int16_t yy_chk[497] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    3,    4,    5,  122,    6,    5,    5,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    9,
       10,  121,   16,    9,   10,   15,   17,   15,   16,   19,
       27,   25,   17,   25,   27,   19,   26,   26,  117,   32,
       19,   32,   16,    9,   10,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   18,   20,   33,   21,   60,   60,
       18,   20,   33,   21,   38,   45,   38,   45,   61,  109,
       61,   18,   20,   21,   22,   22,   22,   34,   22,   22,
       22,   22,   50,   34,   51,   53,   54,   62,   50,   62,
       51,   53,   54,   34,   64,   64,   54,   53,   22,   22,
       22,   51,   22,   35,   35,   35,   52,   35,   35,   35,
       35,   55,   52,   66,   66,   67,   74,   55,   74,   67,
       79,   85,   52,   85,   55,  102,   79,   35,   35,   35,

       80,   35,   86,   89,   86,   90,   80,   91,   92,   89,
       80,   90,  101,   91,   92,   93,   95,   96,   89,   92,
       91,   93,   95,   96,   90,   97,   98,   99,  100,  103,
       82,   97,   98,   99,  100,  103,  103,   93,  104,  100,
      105,   99,   98,  106,  104,   97,  105,  107,  108,  106,
      110,  104,  111,  107,  108,   81,  110,   78,  111,  114,
      112,  106,   77,  107,  113,  114,  112,   75,  108,  110,
      113,  113,  111,  112,  115,  116,  118,  119,  120,   68,
      115,  116,  118,  119,  120,   59,   57,   56,   49,  116,
       48,  115,  118,  124,  124,  124,  124,  124,  124,  124,

      124,  124,  124,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  127,  127,   46,  127,  127,  127,   28,
      127,  127,  128,  128,  128,  128,  128,  128,   24,  128,
      128,  129,   13,    0,    0,  129,  129,    0,  129,  130,
      130,    0,  130,  130,  130,  130,  130,  130,  130,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  132,
      132,    0,  132,  132,  132,  132,  132,  132,  132,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  135,  135,

      135,  135,  135,  135,  135,    0,  135,  136,  136,    0,
      136,  136,  136,    0,  136,  136,  137,  137,  137,  137,
      137,  137,    0,  137,  137,  138,    0,    0,    0,  138,
      138,    0,  138,  139,  139,    0,  139,  139,    0,  139,
      139,  139,  140,  140,  140,  140,  140,    0,  140,  140,
      140,  141,    0,  141,    0,  141,  142,  142,    0,    0,
      142,  142,  142,  142,  142,  142,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[35] =
    {   0,
0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 
    1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,     };

extern int typ__flex_debug;
int typ__flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up typ_text */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( typ_text ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	typ_leng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char typ_text[YYLMAX];
char *yytext_ptr;
#line 1 "tcltk/generic/interface/typelex.l"
#line 2 "tcltk/generic/interface/typelex.l"
/*
 *  TypeExtractor.l
 *  by Kirk Abbott and Ben Allan
 *  Created: 1/94
 *  Version: $Revision: 1.20 $
 *  Version control file: $RCSfile: typelex.l,v $
 *  Date last modified: $Date: 2003/08/23 18:43:09 $
 *  Last modified by: $Author: ballan $
 *
 *  This file is part of the ASCEND Tcl/Tk interface
 *
 *  Copyright 1997, Carnegie Mellon University
 *
 *  The ASCEND Tcl/Tk interface is free software; you can redistribute
 *  it and/or modify it under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of the
 *  License, or (at your option) any later version.
 *
 *  The ASCEND Tcl/Tk interface is distributed in hope that it will be
 *  useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with the program; if not, write to the Free Software Foundation,
 *  Inc., 675 Mass Ave, Cambridge, MA 02139 USA.  Check the file named
 *  COPYING.  COPYING is found in ../compiler.
 */

/*
 *  ASCEND Type Retriever 1.2
 *
 *  Purpose:
 *      To extract a type definition from an input file.
 *  Usage:
 *      See the header file for use from within ASCEND.
 *      For stand-alone use:
 *          typer [flags] ascend_type_name input_file output_file
 *              flags: -c  show comments
 *                         If no -c given, strip out comments.
 *  Features:
 *      --Does not descend into REQUIREd files. Only examines input_file
 *        for definitions of ascend_type_name.
 *      --This version DOES handle the UNIVERSAL quantifier.
 *
 */

#define MY_YYMORE() yymore()

#include <tcl.h>
#include <utilities/ascConfig.h>
#include <general/list.h>
#ifndef TYPER_TEST
/* for handling string modules and results in interp */
#include <compiler/compiler.h>
#include <compiler/symtab.h>
#include <compiler/fractions.h>
#include <compiler/dimen.h>
#include <compiler/child.h>
#include <compiler/type_desc.h>
#include <compiler/library.h>
#include <compiler/module.h>
#include "HelpProc.h" /* help is not necessary for test */
#endif /*!typertest*/

#include "typelex.h"


#ifndef lint
static const char TyperID[] = "$Id: typelex.l,v 1.20 2003/08/23 18:43:09 ballan Exp $";
#endif

#define YY_BREAK
/*
 *  Defining yybreak as above (empty) means that all of our matches must end
 *  in break or return because the normal flex supplied yybreak will
 *  be preempted by our empty one.
 *  In cases where matches contain a conditional return, make sure a
 *  break follows in the failure case.
 */

static int CommentNestLevel = 0;
/*
 *  Nesting level of (* comments *)
 */

static int BracesNestLevel = 0;
/*
 *  Nesting level of {braced} expressions
 */

enum keyword_tokens {
  NONE,       /* Nothing to match, we're in the initial state */
  MODEL,      /* We've just read a MODEL or ATOM keyword */
  MODEL_END,  /* We've just read an END keyword inside a MODEL,
               * an ATOM, or a DEFINITION. */
  CONSTANT    /* We've just read a CONSTANT keyword */
};
static enum keyword_tokens MatchedToken = NONE;
/*
 *  The recognized token we've most recently read.  This usually implies
 *  that we're either in that state or we need to check the next keyword
 *  to see if we should enter (or leave, in the case of MODEL_END) that
 *  state.  MODEL, ATOM, and DEFINITION state are equivalent.
 */

static int ShowComments = 0;
/*
 *  Should we print comments? (1 = yes, 0 = no)
 *  This is set to 1 with `-c' on the command line
 */

static unsigned long StartId = 0;
/*
 *  The location in the `typ_text' array where the MODEL, ATOM, or CONSTANT
 *  identifierbegins.  We save this value and call MY_YYMORE() when we find
 *  a MODEL, ATOM, or CONSTANT keyword; StartId tells us where the
 *  Identifier will go.
 */

static char *reqType = "";
/*
 *  The type we are looking for.  This is one of the arguments passed
 *  to Asc_ExtractType() in the argv vector.
 */

static void Asc_PutCode(char *s,FILE *fp);

static Tcl_Interp *g_typ__interp;
/* during parse, set to caller's interp if string result is wanted
 * instead of file.
 */

#ifdef TYPER_TEST
/*
 *  Specify ASCERR, ASCWAR when building stand alone.
 */
#ifdef REIMPLEMENT_STREAM
FILE *ASCERR = stderr;
FILE *ASCWAR = stderr;
#endif
#endif /* TYPER_TEST */






#line 817 "<stdout>"

#define INITIAL 0
#define Comment 1
#define BracedText 2
#define Model 3
#define Constant 4
#define CheckID 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int typ_wrap (void );
#else
extern int typ_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( typ_text, typ_leng, 1, typ_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( typ_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( typ_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, typ_in))==0 && ferror(typ_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(typ_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int typ_lex (void);

#define YY_DECL int typ_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after typ_text and typ_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 167 "tcltk/generic/interface/typelex.l"


	/*
	 *  Code to handle (* Comments *)
	 *
	 *  "(*" puts us into the Comment state.  Comments nest, so in the
	 *  Comment state we need to look for "(*" that increases the nesting
	 *  level and "*)" that will lower it.
	 *  Do NOT try to match \(\*+ since that causes "(****)" to parse
	 *  incorrectly.
	 */

#line 988 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)typ_alloc(YY_STATE_BUF_SIZE  );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! typ_in )
			typ_in = stdin;

		if ( ! typ_out )
			typ_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			typ_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				typ__create_buffer(typ_in,YY_BUF_SIZE );
		}

		typ__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of typ_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 124 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 467 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_prev_more_offset); yyl < typ_leng; ++yyl )
				if ( typ_text[yyl] == '\n' )
					   
    typ_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
#line 180 "tcltk/generic/interface/typelex.l"
case 2:
#line 181 "tcltk/generic/interface/typelex.l"
case 3:
YY_RULE_SETUP
#line 181 "tcltk/generic/interface/typelex.l"
{
				  /*  Match "(" followed by "*" puts us into
				   *  the COMMENT state.  Don't use \*+ since
				   *  that will parse "(***)" incorrectly.
				   *  Initialize the nesting level.
				   *  Print if ShowComments is TRUE and
                                   *  MatchedToken is not NONE
				   */
				  BEGIN(Comment);
				  CommentNestLevel = 1;
				  if( ShowComments && MatchedToken!=NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 196 "tcltk/generic/interface/typelex.l"
{
				  /*  Match "(" followed "*" followed by
				   *  anything that's not "(" nor "*".
				   *  `anything' includes newlines.
				   *  Increase the commment nesting level.
				   *  Print if ShowComments is TRUE and
                                   *  MatchedToken is not NONE.
				   */
				  CommentNestLevel++;
				  if( ShowComments && MatchedToken!=NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 210 "tcltk/generic/interface/typelex.l"
{
				  /*  Match anything not "*" or "(" followed
				   *  by one or more "*"s followed by ")".
				   *  `anything' includes newlines.
				   *  This decreases the comment nesting level
				   *  and kicks us out if we're back to zero.
				   *  Print if ShowComments is TRUE and
                                   *  MatchedToken is not NONE.
				   */
				  CommentNestLevel--;
				  if( CommentNestLevel > 0 ) {
                                    /* more comments */
                                    break;
                                  }
                                  if( MatchedToken == NONE ) {
                                    BEGIN(INITIAL);
                                    break;
                                  }
                                  if( ShowComments ) {
                                    Asc_PutCode( typ_text, typ_out );
                                  }
                                  switch( MatchedToken ) {
                                  case MODEL:
                                    BEGIN(Model);
                                    break;
                                  case CONSTANT:
                                    BEGIN(Constant);
                                    break;
                                  default:
                                    BEGIN(INITIAL);
                                    break;
                                  }
				  break;
                                }
	YY_BREAK
case 6:
/* rule 6 can match eol */
#line 245 "tcltk/generic/interface/typelex.l"
case 7:
/* rule 7 can match eol */
#line 246 "tcltk/generic/interface/typelex.l"
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 246 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  These three rules eat:
				   *    -- anything that's not a "*" or a "("
				   *    -- "("s not followed by "*"
				   *    -- "*"s not followed by ")"
				   *  `anything' includes newlines.
				   *  Print if ShowComments is TRUE and
                                   *  MatchedToken is not NONE
				   */
				  if( ShowComments && MatchedToken!=NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
/*
	 *  Code to handle { Text in Braces }
	 *
	 *  "{" puts us into the BracedText state.  Braces nest, so
	 *  in the BracedText state we need to look for "{" that increases
	 *  the nesting level and "}" that will lower it.
	 */
case 9:
#line 272 "tcltk/generic/interface/typelex.l"
case 10:
#line 273 "tcltk/generic/interface/typelex.l"
case 11:
YY_RULE_SETUP
#line 273 "tcltk/generic/interface/typelex.l"
{
				  /*  A "{" puts us into the BracedText state.
				   *  Initialize the nesting level.
				   *  Print if MatchedToken is not NONE.
				   *
				   */
				  BEGIN(BracedText);
				  BracesNestLevel = 1;
				  if( MatchedToken != NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 286 "tcltk/generic/interface/typelex.l"
{
				  /*  A backslash \ in the BracedText state
				   *  protects any character---even a
				   *  newline---and does not affect the
				   *  Nesting Level.
				   *  Print if MatchedToken is not NONE.
				   */
				  if( MatchedToken != NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 298 "tcltk/generic/interface/typelex.l"
{
				  /*  A backslash \ in the BracedText state
				   *  protects any character---even a
				   *  newline---and does not affect the
				   *  Nesting Level.
				   *  Print if MatchedToken is not NONE.
				   */
				  if( MatchedToken != NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 310 "tcltk/generic/interface/typelex.l"
{
				  /*  A "{" in the braces state gets added to
				   *  the text and increase the nesting level.
				   *  Match any non-brace character---including
				   *  newlines---that follows the open brace.
				   *  Print if MatchedToken is not NONE.
				   */
				  BracesNestLevel++;
				  if( MatchedToken != NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 323 "tcltk/generic/interface/typelex.l"
{
				  /*  A "}" will reduce the nesting level.
				   *  If the nesting level is zero, go back to
				   *  the previous state.  Match any
				   *  non-brace character---including
				   *  newlines---that precedes the close brace.
				   *  Print if MatchedToken is not NONE.
				   */
				  BracesNestLevel--;
				  if (BracesNestLevel > 0) {
                                    /* more braced text */
                                    break;
                                  }
                                  if( MatchedToken == NONE ) {
                                    BEGIN(INITIAL);
                                    break;
                                  }
                                  Asc_PutCode( typ_text, typ_out );
                                  switch( MatchedToken ) {
				  case MODEL:
                                    BEGIN(Model);
                                    break;
                                  case CONSTANT:
                                    BEGIN(Constant);
                                    break;
                                  default:
                                    BEGIN(INITIAL);
                                    break;
                                  }
				  break;
				}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 354 "tcltk/generic/interface/typelex.l"
{
				  /*  Match anything that is not "{" nor "}"
				   *  nor "\\"(backslash).
				   *  `anything' includes newlines.
				   *  Print if MatchedToken is not NONE.
				   */
				  if( MatchedToken != NONE ) {
				    Asc_PutCode( typ_text, typ_out );
				  }
				  break;
				}
	YY_BREAK
/*
	 *  Code to check an identifier.
	 *
	 *  When we are looking for a MODEL, ATOM, CONSTANT, or DEFIITION
	 *  and we find the text [UNIVERSAL]{MODEL|ATOM|CONSTANT|DEFINITION},
	 *  we enter this state.
         *
         *  When we are insided MODEL, ATOM, or DEFINITION and we find
	 *  the text END, we enter this state.
	 *
	 *  This state checks to see if the text following the MODEL,
	 *  ATOM, CONSTANT, DEFINITION, or END keyword matches
	 *  `reqType'---the type requested by the user.  If so, we are
	 *  at the beginning or end of a type, and should change states
	 *  accordingly.  If not, we should stay in our current state.
	 */
case 17:
YY_RULE_SETUP
#line 385 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  Found an identifier.
				   *  Identify the correct state.
				   */
				  if( MatchedToken == MODEL_END ) {
				    /*
				     *  We're in the Model state, print the
				     *  text and see if matches reqType, if
				     *  so, we're at the end of the MODEL
				     *  (or ATOM or DEFINITION)
				     *  and should exit typ_lex()---return to
				     *  our caller, else stay in the Model
				     *  state.
				     */
				    Asc_PutCode( typ_text, typ_out );
				    if(strcmp((typ_text+StartId),reqType) == 0) {
				      return 0;
				    } else {
                                      MatchedToken = MODEL;
				      BEGIN(Model);
				    }
                                    break;
				  }
                                  if(strcmp((typ_text+StartId),reqType)==0){
				    /*
				     *  We're in the INITIAL state, and we
				     *  found the beginning of the
				     *  requested MODEL, ATOM, CONSTANT,
				     *  or DEFINITION.
				     *  Print the text and set OutputState to
				     *  say we are printing.  Start the
				     *  appropriate State by checking
				     *  MatchedToken.
				     */
				    Asc_PutCode( typ_text, typ_out );
                                    switch( MatchedToken ) {
				    case MODEL:
				      BEGIN(Model);
                                      break;
				    case CONSTANT:
				      BEGIN(Constant);
                                      break;
                                    default:
				      /* something is wrong */
				      BEGIN(INITIAL);
                                      break;
				    }
                                    break;
				  }
                                  /*
                                   *  We're in the INITIAL state; we found
                                   *  an MODEL, ATOM, CONSTANT, or
                                   *  DEFINITION, but it wasn't the right
                                   *  one.  Stay in the INITIAL state.
                                   */
                                  MatchedToken = NONE;
                                  BEGIN(INITIAL);
				  break;
				}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 445 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  Some text other than an identifier
				   *  was found.  Print the text if
				   *  MatchedToken is not NONE,
				   *  and return to the correct state.
				   */
				  if( MatchedToken == NONE ) {
                                    BEGIN(INITIAL);
                                    break;
                                  }
                                  Asc_PutCode( typ_text, typ_out );
                                  switch( MatchedToken ) {
                                  case MODEL:
				    BEGIN(Model);
                                    break;
				  case CONSTANT:
				    BEGIN(Constant);
                                    break;
                                  default:
                                    /* something is wrong */
                                    BEGIN(INITIAL);
                                    break;
				  }
				  break;
				}
	YY_BREAK
/*
	 *  Code to handle the model/atom/definition we want.
	 *
	 *  Once we've found the start of the matching MODEL, ATOM, or
         *  DEFINITION, print the text until we find the END token.
         *  When we find END, save the current length of typ_text and use
         *  MY_YYMORE() to append the identifier, then check the identifier
         *  (in the CheckID state) to see if it is what we want.  If so,
	 *  this is the end of this MODEL, ATOM, or DEFINITION.
	 */
case 19:
YY_RULE_SETUP
#line 485 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  Found the END keyword.  Save the
				   *  current location in the typ_text array,
				   *  then enter the CheckID state to see if
				   *  the identifier matches what we want.
				   */
				  StartId = typ_leng;
                                  MatchedToken = MODEL_END;
				  BEGIN(CheckID);
				  MY_YYMORE();
				  break;
				}
	YY_BREAK
case 20:
/* rule 20 can match eol */
#line 499 "tcltk/generic/interface/typelex.l"
case 21:
/* rule 21 can match eol */
#line 500 "tcltk/generic/interface/typelex.l"
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 500 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  These rules match
				   *    -- any character except that which
				   *       would cause us to change states
				   *    -- "("s not followed by "*"s
				   *    -- uppercase keywords and following
				   *       semicolon or whitespace.
				   *  Print the text.
				   */
				  Asc_PutCode( typ_text, typ_out );
				  break;
				}
	YY_BREAK
/*
	 *  Code to handle the constant definition we want.
	 *
	 *  Once we've found the start of the matching CONSTANT, print
	 *  the text until we find a semicolon ";".
	 */
case 23:
YY_RULE_SETUP
#line 523 "tcltk/generic/interface/typelex.l"
{
				  /*
				   * Found the ";" which ends the CONSTANT.
				   * Do NOT print it since that will be
				   * added below.  Return 0.
				   */
				   return 0;
				}
	YY_BREAK
case 24:
/* rule 24 can match eol */
#line 532 "tcltk/generic/interface/typelex.l"
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 532 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  These rules match
				   *    -- any character except that which
				   *       would cause us to change states
				   *    -- "("s not followed by "*"s
				   *  Print the text.
				   */
				  Asc_PutCode( typ_text, typ_out );
				  break;
				}
	YY_BREAK
/*
	 *  Code to look for [UNIVERSAL ]{MODEL|ATOM|CONSTANT|DEFINITION}.
	 *
	 *  If we find UNIVERSAL, use yymore() to append the next
	 *  keyword---probably MODEL, ATOM, or CONSTANT.
	 *  If we find MODEL, ATOM, CONSTANT, or DEFINITION save the
	 *  current length and use yymore() to append the identifier,
	 *  then check the identifier (in the CheckID state) to see if
	 *  it is what we're looking for.
	 */
case 26:
YY_RULE_SETUP
#line 557 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  Found the UNIVERSAL keyword.  Append
				   *  the following ATOM/MODEL/CONSTANT
				   *  keyword.
				   */
				  MY_YYMORE();
				  break;
				}
	YY_BREAK
case 27:
#line 567 "tcltk/generic/interface/typelex.l"
case 28:
#line 568 "tcltk/generic/interface/typelex.l"
case 29:
YY_RULE_SETUP
#line 568 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  Found an MODEL, ATOM, or DEFINITION
				   *  keyword--perhaps with a UNIVERSAL
				   *  modifier.  Save the current location
				   *  in the typ_text array, then enter the
				   *  CheckID state to see if the identifier
                                   *  matches what we want.
				   */
				  StartId = typ_leng;
				  MatchedToken = MODEL;
				  BEGIN(CheckID);
				  MY_YYMORE();
				  break;
				}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 583 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  Found a CONSTANT keyword--perhaps
				   *  with a UNIVERSAL modifier.  Save the
				   *  current location in the typ_text array,
				   *  then enter the CheckID state to see if
				   *  the identifier matches what we want.
				   */
				  StartId = typ_leng;
				  MatchedToken = CONSTANT;
				  BEGIN(CheckID);
				  MY_YYMORE();
				  break;
				}
	YY_BREAK
/*
         *  Rules to match other text.
         */
case 31:
/* rule 31 can match eol */
#line 606 "tcltk/generic/interface/typelex.l"
case 32:
/* rule 32 can match eol */
#line 607 "tcltk/generic/interface/typelex.l"
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 607 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  These rules match
				   *    -- any character except that which
				   *       would cause us to change states
				   *    -- "("s not followed by "*"s
				   *    -- uppercase keywords and following
				   *       semicolon or whitespace.
				   *  Do nothing.
				   */
				  break;
				}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 619 "tcltk/generic/interface/typelex.l"
{
				  /*
				   *  Reached End of file without a match
				   */
				  return 1;
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 627 "tcltk/generic/interface/typelex.l"
ECHO;
	YY_BREAK
#line 1629 "<stdout>"
			case YY_STATE_EOF(Comment):
			case YY_STATE_EOF(BracedText):
			case YY_STATE_EOF(Model):
			case YY_STATE_EOF(Constant):
			case YY_STATE_EOF(CheckID):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed typ_in at a new source and called
			 * typ_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = typ_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( typ_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * typ_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of typ_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			typ_restart(typ_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 124 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 124 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 123);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up typ_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --typ_lineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					typ_restart(typ_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( typ_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve typ_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    typ_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void typ_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        typ_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            typ__create_buffer(typ_in,YY_BUF_SIZE );
	}

	typ__init_buffer(YY_CURRENT_BUFFER,input_file );
	typ__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void typ__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		typ_pop_buffer_state();
	 *		typ_push_buffer_state(new_buffer);
     */
	typ_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	typ__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (typ_wrap()) processing, but the only time this flag
	 * is looked at is after typ_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void typ__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	typ_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE typ__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) typ_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in typ__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) typ_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in typ__create_buffer()" );

	b->yy_is_our_buffer = 1;

	typ__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with typ__create_buffer()
 * 
 */
    void typ__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		typ_free((void *) b->yy_ch_buf  );

	typ_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a typ_restart() or at EOF.
 */
    static void typ__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	typ__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then typ__init_buffer was _probably_
     * called from typ_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void typ__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		typ__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void typ_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	typ_ensure_buffer_stack();

	/* This block is copied from typ__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from typ__switch_to_buffer. */
	typ__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void typ_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	typ__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		typ__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void typ_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)typ_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)typ_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE typ__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) typ_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in typ__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	typ__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to typ_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       typ__scan_bytes() instead.
 */
YY_BUFFER_STATE typ__scan_string (yyconst char * yystr )
{
    
	return typ__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to typ_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE typ__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) typ_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in typ__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = typ__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in typ__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up typ_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		typ_text[typ_leng] = (yy_hold_char); \
		(yy_c_buf_p) = typ_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		typ_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int typ_get_lineno  (void)
{
        
    return typ_lineno;
}

/** Get the input stream.
 * 
 */
FILE *typ_get_in  (void)
{
        return typ_in;
}

/** Get the output stream.
 * 
 */
FILE *typ_get_out  (void)
{
        return typ_out;
}

/** Get the length of the current token.
 * 
 */
int typ_get_leng  (void)
{
        return typ_leng;
}

/** Get the current token.
 * 
 */

char *typ_get_text  (void)
{
        return typ_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void typ_set_lineno (int  line_number )
{
    
    typ_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see typ__switch_to_buffer
 */
void typ_set_in (FILE *  in_str )
{
        typ_in = in_str ;
}

void typ_set_out (FILE *  out_str )
{
        typ_out = out_str ;
}

int typ_get_debug  (void)
{
        return typ__flex_debug;
}

void typ_set_debug (int  bdebug )
{
        typ__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from typ_lex_destroy(), so don't allocate here.
     */

    /* We do not touch typ_lineno unless the option is enabled. */
    typ_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    typ_in = stdin;
    typ_out = stdout;
#else
    typ_in = (FILE *) 0;
    typ_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * typ_lex_init()
     */
    return 0;
}

/* typ_lex_destroy is for both reentrant and non-reentrant scanners. */
int typ_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		typ__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		typ_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	typ_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    typ_free ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * typ_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *typ_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *typ_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void typ_free (void * ptr )
{
	free( (char *) ptr );	/* see typ_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 627 "tcltk/generic/interface/typelex.l"


/*
 *  int typ_wrap(void);
 *
 *  This returns 1 if the scanner should stop parsing, or 0 if
 *  the scanner should continue.  Flex requires this function
 *  unless the flex directive `%option nozzwrap' is given, but
 *  `%option' directives are a recent addition to flex and for
 *  maximum portability should not be used.
 */
int typ_wrap(void)
{
  return 1;
}


#ifndef TYPER_TEST
STDHLF(Asc_ExtractType,(Asc_ExtractTypeHL1,Asc_ExtractTypeHL2,HLFSTOP));
#endif

/*
 *  int Asc_ExtractType(cdata, interp, argc, argv)
 *      ClientData cdata;    --Tcl information, not used
 *      Tcl_Interp *interp;  --Tcl interpreter, not used in standalone use
 *      int argc;            --the number of arguments
 *      char **argv;         --the array of arguments
 *
 *  When running as part of ASCEND, returns TCL_OK or TCL_ERROR.
 *  When running as a stand alone tool (CPP macro TYPER_TEST is defined)
 *  we return:
 *    0  --success
 *    1  --problems with arguments
 *    2  --problems opening file
 *   -1  --no errors occurred but the requested type was not found
 *
 */
extern int Asc_ExtractType(ClientData cdata, Tcl_Interp *interp,
                           int argc, CONST84 char **argv)
{
  int ndx = 1;   /* index into the argv array */
  int result;    /* result from typ_lex and value to return to caller */
#ifndef TYPER_TEST
  struct TypeDescription *desc=NULL;
  struct module_t *mod=NULL;
  CONST char *scanstring=NULL;
  YY_BUFFER_STATE oldbuf=NULL;
  YY_BUFFER_STATE scanbuf=NULL;
#endif /*!typertest*/

  (void)cdata;   /* stop gcc whining about unused parameter */
#ifdef TYPER_TEST
  (void)interp;  /* stop gcc whining about unused parameter */
#endif


  /*
   *  Reset our global set
   */
  BEGIN( INITIAL );
  MatchedToken = NONE;
  ShowComments = 0;
  reqType = "";
  CommentNestLevel = 0;
  BracesNestLevel = 0;


  /*
   *  Process the arguments
   */
  if (( argc < 2 ) || ( argc > 5 )) {
#ifdef TYPER_TEST
    FPRINTF(ASCERR,
            "Wrong number of arguments\n"
            "Usage: %s [-c] type [source_file] [destination_file]\n",
            argv[0]);
    return 1;
#else /* ! TYPER_TEST */
    Tcl_AppendResult(interp, "Wrong number of arguments\nUsage: ",
		     argv[0], "[-c] type [source_file] "
                     "[-s,destination_file]",
		     (char*)NULL);
    return TCL_ERROR;
#endif /* TYPER_TYPER */
  }

  if(( argc > ndx ) && ( argv[ndx][0] == '-' )) {
    switch( argv[ndx][1] ) {
    case 'c':
      ShowComments = 1;
      ndx++;
      break;
    default:
#ifdef TYPER_TEST
      FPRINTF(ASCERR, "Unknown switch %s\n", argv[ndx]);
      return 1;
#else /* ! TYPER_TEST */
      Tcl_AppendResult(interp, "Unknown switch ", argv[ndx], (char*)NULL);
      return TCL_ERROR;
#endif /* TYPER_TEST */
    }
  }

  if( argc > ndx ) {
    /*  The type of MODEL/ATOM to get  */
    reqType = QUIET(argv[ndx++]);
  } else {
#ifdef TYPER_TEST
    FPRINTF(ASCERR,
            "Wrong number of arguments\n"
            "Usage: %s [-c] type [source_file] [destination_file]\n",
            argv[0]);
    return 1;
#else /* ! TYPER_TEST */
    Tcl_AppendResult(interp, "Wrong number of arguments\nUsage: ",
		     argv[0], "[-c] type [source_file] "
                     "[-s,destination_file]",
		     (char*)NULL);
      return TCL_ERROR;
#endif /* TYPER_TEST */
  }

  if( argc > ndx ) {
    /*  The source file; stdin if not specified. */
#ifndef TYPER_TEST
    /* in ascend, find source module if possible for string module name */
    desc = FindType(AddSymbol(reqType));
    if (desc != NULL) {
      mod = GetModule(desc);
      assert(mod!=NULL);
      scanstring = Asc_ModuleString(mod);
      if (scanstring == NULL) {
        mod = NULL;
      }
    }
#endif /*!typertest*/
    if(scanstring == NULL && (typ_in = fopen(argv[ndx],"r")) == NULL) {
#ifdef TYPER_TEST
      FPRINTF(ASCERR, "Error opening source file \'%s\'\n", argv[ndx]);
      return 2;
#else /* ! TYPER_TEST */
      Tcl_AppendResult(interp, "Error opening source file \'",
                       argv[ndx], "\'", (char*)NULL);
      return TCL_ERROR;
#endif /* TYPER_TEST */
    }
    ndx++;
  } else {
    typ_in = stdin;
  }

  if( argc > ndx ) {
#ifndef TYPER_TEST
    if (argv[ndx][0] == '-' && argv[ndx][1] == 's') {
      g_typ__interp = interp;
      typ_out = NULL;
    } else {
#endif /* !typertest*/
      g_typ__interp = NULL;
      /*  The destination file; stdout if not specified  */
      if((typ_out = fopen(argv[ndx],"a+")) == NULL) {
#ifdef TYPER_TEST
        FPRINTF(ASCERR, "Error opening destination file \'%s\'\n", argv[ndx]);
        return 2;
#else /* ! TYPER_TEST */
        Tcl_AppendResult(interp, "Error opening destination file \'",
                         argv[ndx], "\'", (char*)NULL);
        return TCL_ERROR;
#endif /* TYPER_TEST */
      }
#ifndef TYPER_TEST
    }
#endif /* !typertest*/
    ndx++;
  } else {
    typ_out = stdout;
  }


  /*
   *  Call typ_lex() to process the input
   */
#ifndef TYPER_TEST
  if (scanstring != NULL) {
    oldbuf = YY_CURRENT_BUFFER;
    scanbuf = typ__scan_string(scanstring);
    typ__switch_to_buffer(scanbuf);
    BEGIN(INITIAL);
    /* typ_restart((FILE *)NULL); */
  }
#else
  typ_restart(typ_in);
#endif /* !typertest */
  if( (result = typ_lex()) != 0 ) {
#ifdef TYPER_TEST
    FPRINTF(ASCERR, "Could not find type \'%s\'\n", reqType);
#else /* ! TYPER_TEST */
    if (g_typ__interp!=NULL) {
      Tcl_ResetResult(interp);
    }
    Tcl_AppendResult(interp, "Could not find type \'", reqType, "\'",
                     (char*)NULL);
    result = TCL_ERROR;
#endif /* TYPER_TEST */
  } else {
    /* add a closing semicolon and newline */
    Asc_PutCode( ";\n", typ_out );
#ifndef TYPER_TEST
    result = TCL_OK;
#endif /* ! TYPER_TEST */
  }

  /*
   *  Close any files/buffers we opened and exit.
   */
#ifndef TYPER_TEST
  if (scanstring != NULL) {
    typ__delete_buffer(YY_CURRENT_BUFFER);
    typ__switch_to_buffer(oldbuf);
    BEGIN(INITIAL);
  }
#endif
  if ( typ_in != stdin && typ_in != NULL) {
    fclose(typ_in);
  }
  if ( typ_out != stdout && typ_out != NULL) {
    fclose(typ_out);
  }

  return result;
}

static void Asc_PutCode(char *s,FILE *fp)
/** into string or screen */
{
#ifndef TYPER_TEST
  if (g_typ__interp != NULL) {
    Tcl_AppendResult(g_typ__interp,s,(char *)NULL);
  } else {
#endif /* typertest */
    fputs(s,fp);
#ifndef TYPER_TEST
  }
#endif /* typertest */
}

#ifdef TYPER_TEST
int main(int argc, char **argv)
{
  return Asc_ExtractType((ClientData)NULL, (Tcl_Interp*)NULL, argc, argv);
}
#endif /*  TYPER_TEST  */

