#!/usr/bin/env python
Import('env')

if env.get('WITH_DOPRI5'):

	# To run the test, type
	#     ascdev test/dopri5/dopri5.a4c

	dopri5obj = env.SharedObject("dopri5.c")

	lib = env.SharedLibrary("dopri5",["asc_dopri5.c",dopri5obj]
		,LIBS = ['ascend']
		,LIBPATH = ['#']
		,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
		,SHLIBPREFIX = env['EXTLIB_PREFIX']		
	)

	env.Depends(lib,env['libascend'])

	env['extfns'] += lib

	if env.get('CAN_INSTALL'):
		dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
		env.InstallShared(dir,lib)

# vim: set syntax=python:
