Import('env')

if env.get('WITH_DOPRI5'):

# To run the test, type
#     ascdev test/dopri5/dopri5.a4c

dopri5obj = env.SharedObject("dopri5.c")

lib = env.SharedLibrary("dopri5",["asc_dopri5.c",dopri5obj]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']		
)

env['extfns'] += [lib]

# vim: set syntax=python:
