Import('env')

srcs = Split("""
	AscBitmaps.c AscPrintTcl.c BrowLogRel_io.c BrowWhen_io.c
	BrowserMethod.c BrowserProc.c BrowserQuery.c BrowserRel_io.c
	Commands.c DebugProc.c DisplayProc.c
	EnvVarProc.c HelpProc.c Integrators.c
	LibraryProc.c Lsode.c MtxProc.c ProbeProc.c Qlfdid.c
	ScriptProc.c Sensitivity.c SimsProc.c SlvProc.c
	SolverProc.c UnitsProc.c UserData.c
	tkConsole.c old_utils.c
""")


typelex = env.CFile(target='typelex.c',source='typelex.l'
	, LEXFLAGS = '-ll -Pzz'
)

#----------------
libs = Split("""
	asccompiler ascpackages ascsolver ascutilities ascgeneral 
	tcl tk
""")

libpath = [
	'../../../base/generic/compiler'
	,'../../../base/generic/packages'
	,'../../../base/generic/solver'
	,'../../../base/generic/utilities'
	,'../../../base/generic/general'
]

env.Program("ascend4",srcs+typelex+['Driver.c']
	, LIBS = libs
	, LIBPATH = libpath+['$LIBPATH']
	, CPPPATH = ['../../../base/generic']
)

if 0:
	env.Program('ascend4',driver
		, CPPPATH=cpppath
		, LIBS=libs
		, LIBPATH=['../../../base/generic/compiler'
			,'../../../base/generic/packages'
			,'../../../base/generic/solver'
			,'../../../base/generic/utilities'
			,'../../../base/generic/general'
			,'.'
		  ]
	)
