Import('env')

srcs = Split("""
	Driver.c

	AscBitmaps.c AscPrintTcl.c BrowLogRel_io.c BrowWhen_io.c
	BrowserMethod.c BrowserProc.c BrowserQuery.c BrowserRel_io.c
	Commands.c DebugProc.c DisplayProc.c
	EnvVarProc.c HelpProc.c Integrators.c
	LibraryProc.c Lsode.c MtxProc.c ProbeProc.c Qlfdid.c
	ScriptProc.c Sensitivity.c SimsProc.c SlvProc.c
	SolverProc.c UnitsProc.c UserData.c
	tkConsole.c old_utils.c
""")


typelex = env.CFile(target='typelex.c',source='typelex.l'
	, LEXFLAGS = '-Pzz'
)

libs = Split("""
	asccompiler ascpackages ascsolver ascutilities ascgeneral 
	tcl tk
""")

env.Program('ascend4',srcs+typelex
	, CPPPATH=['../../../base/generic','..']
	, LIBS=libs
	, LIBPATH=['../../../base/generic/compiler'
		,'../../../base/generic/packages'
		,'../../../base/generic/solver'
		,'../../../base/generic/utilities'
		,'../../../base/generic/general']
)
