#!/usr/bin/python invoke_using_scons
Import('libascend_env')

csrcs = Split("""
	ascMalloc.c dstring.c except.c
	hashpjw.c list.c listio.c mem.c
	pool.c pretty.c
	stack.c table.c tm_time.c
	ospath.c env.c pairlist.c ltmatrix.c
""")

objs =[]
for c in csrcs:
	objs += libascend_env.SharedObject(c)

#--------------------
# INSTALL

import glob

if libascend_env.get('CAN_INSTALL'):
	installdir = Dir(libascend_env.subst("$INSTALL_ROOT$INSTALL_INCLUDE/ascend/general"))

	headers = glob.glob("*.h")
	libascend_env.InstallHeader(installdir,headers)

Return('objs')

# vim: set syntax=python:

