Import('libascend_env')

csrcs = Split("""
	dstring.c hashpjw.c list.c listio.c pool.c pretty.c
	stack.c table.c tm_time.c
	ospath.c env.c
""")

objs =[]
for c in csrcs:
	objs += libascend_env.SharedObject(c)

Return('objs')
