Import('libascend_env')

csrcs = Split("""
	dstring.c hashpjw.c list.c listio.c pool.c pretty.c
	stack.c table.c tm_time.c
	ospath.c env.c
""")

objs =[]
for c in csrcs:
	objs += libascend_env.SharedObject(c)

#--------------------
# INSTALL

import glob

if libascend_env.get('CAN_INSTALL'):
	installdir = libascend_env['INSTALL_ROOT']+libascend_env['INSTALL_INCLUDE']+'/general'

	headers = glob.glob("*.h")
	libascend_env.InstallHeader(installdir,headers)

Return('objs')

# vim: set syntax=python:

