Import('env')

# To run the test, type
#     ascdev sensitivity_test.a4c

for e in ['sensitivity','solve','finitediff']:
	env['extfns'] += [env.SharedLibrary(e,["%s.c" % e]
		,LIBS = ['ascend']
		,LIBPATH=['#']
		,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
		,SHLIBPREFIX = env['EXTLIB_PREFIX']
	)]

# vim: set syntax=python:
