/*********************************************************************\
                           CodeGeneration Support Code
			   by Kirk Andre Abbott.
			   
  This file should be included by all code that was generated by
  ASCEND.
\*********************************************************************/


#ifndef __codegen_support_H_SEEN__
#define __codegen_support_H_SEEN__

struct CG_Problem {
  int number_relations;
  int number_variables;
  int number_incidences;
  int number_inputs;
  int number_outputs;
  int sizeof_x_vector;
  int sizeof_u_vector;
  int sizeof_f_vector;
  int sizeof_g_vector;
  /*
   * other stuffy.
   */
  int *ha;
  int *ka;
  int *vartypes;
  int *reltypes;
  int *inputs;
  int *outputs;
  double *u;
  void *user_data;
};

#define CG_Problem_Init(p,prefix,x,u,lo,up,nom) \
    ((prefix)##__Initialize(p,x,u,lo,up,nom))

#ifdef STAND_ALONE
typedef int ExtEvalFunc(int *mode, int *m, int *n,
			double *x, double *u, double *f, double *g);
#else
#include "compiler.h"
#include "extfunc.h"
#endif	/* STAND_ALONE */


#endif /* __codegen_support_H_SEEN__ */



