Import('fprops_env')
test_env = fprops_env.Clone()

shobj_names = [str(o) for o in test_env.get('shobjs', [])]
have_eqm_ipopt_obj = any('eqm_ipopt.' in s for s in shobj_names)
have_eqm_slsqp_obj = any('eqm_slsqp.' in s for s in shobj_names)

testsrcs = ['ideal.c','ph.c','sat1.c','sat.c','visc.c']

#print "srcs =",srcs

#for s in testsrcs:
#	test_env.Program([s] + test_env['shobjs']
#		,LIBS = ["m"]
#		,LIBPATH = "#"
#	)

#print "CUNIT_CPPPATH =",test_env.get("CUNIT_CPPPATH")

test_env['WITH_IPOPT'] = 1 if test_env.ensure_ipopt() else 0
test_env['WITH_NLOPT'] = 1 if test_env.get('HAVE_NLOPT') else 0

if test_env['WITH_CUNIT']:
	test_env.AppendUnique(
		CPPPATH=test_env.get('CUNIT_CPPPATH',[])
		,LIBPATH=test_env.get('CUNIT_LIBPATH',[])
	)

	cutest_libs = ['m','cunit']

	tobjs = []
	for f in test_env['fluids']:
		tobjs += [test_env.SharedObject(f
			,CPPDEFINES=['-DTEST','-DCUNIT_TEST']
			,OBJPREFIX='#/test/cutest-fluid-'
		)]

	tobjs += [
		test_env.SharedObject('cutest.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('cutest_pengrob_rpp.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('mixture_ideal.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('cutest_eqm.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('cutest_refstate.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('../test.c')
	]
	if test_env.get('WITH_IPOPT'):
		cutest_libs += list(test_env.get('IPOPT_LIBS') or ['ipopt'])
	if test_env.get('WITH_NLOPT'):
		cutest_libs.append('nlopt')

	cutest_prog = test_env.Program('cutest', test_env['shobjs'] + tobjs
		,LIBS = cutest_libs
	)
	test_env.Alias('cutest', cutest_prog)

if test_env.get('WITH_IPOPT'):
	test_env.AppendUnique(CPPPATH=['#'])
	test_env.AppendUnique(CPPDEFINES=['HAVE_IPOPT'])
	test_env.AppendUnique(CPPPATH=test_env.get('IPOPT_CPPPATH', []))
	test_env.AppendUnique(LIBPATH=test_env.get('IPOPT_LIBPATH', []))
	test_env.AppendUnique(LIBS=test_env.get('IPOPT_LIBS', []))
	if test_env.get('WITH_NLOPT'):
		test_env.AppendUnique(CPPDEFINES=['HAVE_NLOPT'])
		test_env.AppendUnique(CPPPATH=test_env.get('NLOPT_CPPPATH', []))
		test_env.AppendUnique(LIBPATH=test_env.get('NLOPT_LIBPATH', []))
		test_env.AppendUnique(LIBS=test_env.get('NLOPT_LIBS', []))
	ipopt_solver_objs = []
	if test_env.get('WITH_IPOPT') and not have_eqm_ipopt_obj:
		ipopt_solver_objs.append(
			test_env.SharedObject('../eqm_ipopt.c',OBJPREFIX='#/test/ipopt-lib-')
		)
	if test_env.get('WITH_NLOPT') and not have_eqm_slsqp_obj:
		ipopt_solver_objs.append(
			test_env.SharedObject('../eqm_slsqp.c',OBJPREFIX='#/test/ipopt-lib-')
		)
	ipopt_objs = ipopt_solver_objs + [
		test_env.SharedObject('ipopt_eqm.c',OBJPREFIX='#/test/ipopt-test-')
	]
	ipopt_libs = ['m'] + list(test_env.get('IPOPT_LIBS') or ['ipopt'])
	if test_env.get('WITH_NLOPT'):
		ipopt_libs.append('nlopt')
	ipopt_eqm_prog = test_env.Program('ipopt_eqm', test_env['shobjs'] + ipopt_objs
		,LIBS = ipopt_libs
	)
	test_env.Alias('ipopt_eqm', ipopt_eqm_prog)
	cmp_objs = ipopt_solver_objs + [
		test_env.SharedObject('eqm_case_runner.c',OBJPREFIX='#/test/eqmcmp-test-')
	]
	eqm_case_runner_prog = test_env.Program('eqm_case_runner', test_env['shobjs'] + cmp_objs
		,LIBS = ipopt_libs
	)
	test_env.Alias('eqm_case_runner', eqm_case_runner_prog)
	nox_objs = ipopt_solver_objs + [
		test_env.SharedObject('eqm_nox_runner.c',OBJPREFIX='#/test/eqmnox-test-')
	]
	eqm_nox_runner_prog = test_env.Program('eqm_nox_runner', test_env['shobjs'] + nox_objs
		,LIBS = ipopt_libs
	)
	test_env.Alias('eqm_nox_runner', eqm_nox_runner_prog)
	mu0_objs = ipopt_solver_objs + [
		test_env.SharedObject('eqm_mu0_runner.c',OBJPREFIX='#/test/eqmmu0-test-')
	]
	eqm_mu0_runner_prog = test_env.Program('eqm_mu0_runner', test_env['shobjs'] + mu0_objs
		,LIBS = ipopt_libs
	)
	test_env.Alias('eqm_mu0_runner', eqm_mu0_runner_prog)
	pureprops_objs = ipopt_solver_objs + [
		test_env.SharedObject('pureprops_compare.c',OBJPREFIX='#/test/pureprops-test-')
	]
	pureprops_compare_prog = test_env.Program('pureprops_compare', test_env['shobjs'] + pureprops_objs
		,LIBS = ipopt_libs
	)
	test_env.Alias('pureprops_compare', pureprops_compare_prog)
