Import('fprops_env')
test_env = fprops_env.Clone()

testsrcs = ['ideal.c','ph.c','sat1.c','sat.c','visc.c']

#print "srcs =",srcs

#for s in testsrcs:
#	test_env.Program([s] + test_env['shobjs']
#		,LIBS = ["m"]
#		,LIBPATH = "#"
#	)

#print "CUNIT_CPPPATH =",test_env.get("CUNIT_CPPPATH")

if test_env['WITH_CUNIT']:
	test_env.AppendUnique(
		CPPPATH=test_env.get('CUNIT_CPPPATH',[])
		,LIBPATH=test_env.get('CUNIT_LIBPATH',[])
	)

	tobjs = []
	for f in test_env['fluids']:
		tobjs += [test_env.SharedObject(f
			,CPPDEFINES=['-DTEST','-DCUNIT_TEST']
			,OBJPREFIX='#/test/cutest-fluid-'
		)]

	tobjs += [
		test_env.SharedObject('cutest.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('cutest_pengrob_rpp.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('mixture_ideal.c',OBJPREFIX='#/test/cutest-')
		, test_env.SharedObject('../test.c')
	]

	test_env.Program('cutest', test_env['shobjs'] + tobjs
		,LIBS = ['m','cunit']
	)

if not test_env.get('WITH_IPOPT'):
	try:
		test_env.ParseConfig('pkgconf ipopt --libs --cflags')
		test_env['WITH_IPOPT'] = 1
	except OSError:
		test_env['WITH_IPOPT'] = 0

if not test_env.get('WITH_NLOPT'):
	try:
		test_env.ParseConfig('pkgconf nlopt --libs --cflags')
		test_env['WITH_NLOPT'] = 1
	except OSError:
		test_env['WITH_NLOPT'] = 0

if test_env.get('WITH_IPOPT'):
	test_env.AppendUnique(CPPPATH=['#'])
	test_env.AppendUnique(CPPDEFINES=['HAVE_IPOPT'])
	if test_env.get('WITH_NLOPT'):
		test_env.AppendUnique(CPPDEFINES=['HAVE_NLOPT'])
	try:
		test_env.ParseConfig('pkgconf ipopt --libs --cflags')
	except OSError:
		pass
	if test_env.get('WITH_NLOPT'):
		try:
			test_env.ParseConfig('pkgconf nlopt --libs --cflags')
		except OSError:
			pass
	ipopt_objs = [
		test_env.SharedObject('ipopt_eqm.c',OBJPREFIX='#/test/ipopt-test-')
		,test_env.SharedObject('../eqm.c',OBJPREFIX='#/test/ipopt-lib-')
		,test_env.SharedObject('../eqm_ipopt.c',OBJPREFIX='#/test/ipopt-lib-')
	]
	if test_env.get('WITH_NLOPT'):
		ipopt_objs.append(test_env.SharedObject('../eqm_slsqp.c',OBJPREFIX='#/test/ipopt-lib-'))
	ipopt_libs = ['m','ipopt']
	if test_env.get('WITH_NLOPT'):
		ipopt_libs.append('nlopt')
	test_env.Program('ipopt_eqm', test_env['shobjs'] + ipopt_objs
		,LIBS = ipopt_libs
	)
