Import('env')
grena_env = env.Clone()

srcs = Split("""
	sunpos_grena.c
	asc_sunpos.c
""")

grena_env.Append(LIBPATH=['#'])
grena_env.Append(LIBS=['ascend'])

lib = grena_env.SharedLibrary("sunpos",srcs
	,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
	,SHLIBPREFIX = env['EXTLIB_PREFIX']
)

env['extfns'] += [lib]

# vim: set syntax=python:
