#!/usr/bin/python invoke_using_scons
Import('libascend_env')

csrcs = Split("""
	ascDynaLoad.c ascEnvVar.c
	ascPrint.c 
	bit.c 
	error.c readln.c set.c
""")

configh = libascend_env.SubstInFile(source='config.h.in')

objs = []
for c in csrcs:
	objs += libascend_env.SharedObject(c)

sig_env = libascend_env.Clone()
sig_env.Append(CPPDEFINES=['NO_SIGINT_TRAP','NO_SIGSEGV_TRAP'])
objs += sig_env.SharedObject('ascSignal.c')

#--------------------
# INSTALL

import glob

if libascend_env.get('CAN_INSTALL'):
	installdir = Dir(libascend_env.subst("$INSTALL_ROOT$INSTALL_INCLUDE/ascend/utilities"))

	headers = glob.glob("*.h")
	libascend_env.InstallHeader(installdir,headers)

Return('objs')

# vim: set syntax=python:

