Import('env')
import platform

# build the ASCEND IPOPT solver. we will do any configuration testing here now,
# also, only if the solver is requested.

ipopt_test_text = """
#if !defined(_WIN32)
# define FNAME_LCASE_DECOR
#endif

/* note that pkg-config sets the coin-or directory, so no need to prefix here */
#include <IpStdCInterface.h>
int main(void){
	Number n;
	IpoptProblem nlp = 0;
	n = 1;
	FreeIpoptProblem(nlp);
	return 0;
}
"""

def CheckIPOPT(context):
	context.Message( 'Checking for IPOPT... ' )
	is_ok = context.env.ensure_ipopt()
	if not is_ok:
		context.Result("no (%s)" % (context.env.get('IPOPT_REASON') or 'not found'))
		return False

	context.env.AppendUnique(CPPPATH=context.env.get('IPOPT_CPPPATH', []))
	context.env.AppendUnique(LIBPATH=context.env.get('IPOPT_LIBPATH', []))
	context.env.AppendUnique(LIBS=context.env.get('IPOPT_LIBS', []))
	is_ok = context.TryLink(ipopt_test_text,".c")
	if is_ok:
		context.Result(True)
	else:
		context.env['IPOPT_REASON'] = 'failed to link'
		context.Result("no (failed to link)")
	return is_ok

if env.get('WITH_IPOPT'):
	solver_env = env.Clone()
	
	conf = solver_env.Configure(custom_tests={'CheckIPOPT':CheckIPOPT})
	if not conf.CheckIPOPT():
		conf.env['WITH_IPOPT'] = False
	solver_env = conf.Finish()

	# tell the top-level if our conf test failed
	env.set_optional('ipopt',active=solver_env['WITH_IPOPT'],reason=solver_env.get('IPOPT_REASON') or "not found");
	
	if env['WITH_IPOPT']:
		if platform.system()=="Windows":
			solver_env.Append(
				CFLAGS=["-static"]
			)

		if solver_env.get('IPOPT_CPPPATH'):
			solver_env.AppendUnique(CPPPATH=solver_env['IPOPT_CPPPATH'])
		if solver_env.get('IPOPT_LIBPATH'):
			solver_env.AppendUnique(LIBPATH=solver_env['IPOPT_LIBPATH'])
		if solver_env.get('IPOPT_LIBS'):
			solver_env.AppendUnique(LIBS=solver_env['IPOPT_LIBS'])

		solver_env.Append(LIBS=['ascend'],LIBPATH=['#'])

		lib = solver_env.SharedLibrary("ipopt",["asc_ipopt.c"]
			,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
			,SHLIBPREFIX = env['EXTLIB_PREFIX']
		)
		
		env.Depends(lib,env['libascend'])

		env['extfns'] += [lib]
		
		if 0:
			print(f"IPOPT LIBPATH = {solver_env['LIBPATH']}")
			if len(solver_env['LIBPATH'])==1:
				plusdir = str(Path(solver_env['LIBPATH']).parent.parent/'bin')
				if len(env.get('DLLDIRS')):
					env['DLLDIRS'] + os.pathsep
				env['DLLDIRS'] += plusdir
				# TODO check that libipopt-3.dll is located here....?
			else:
				print("Unexpected length of LIBPATH in IPOPT solver build")
		if env.get('CAN_INSTALL'):
			dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
			env.InstallShared(dir,lib)
	else:
		print("Skipping... IPOPT solver won't be built.")

# vim:syntax=python:sw=4:ts=4:noet
