#!/bin/sh
#
# Use this script to perform the Jam build on Linux
#
# Usage: ./jambuild libs

if [ $SMP ]; then
	smp_flags=$SMP
elif uname -v | grep "SMP"; then
	smp_flags=-j2
else
	smp_flags=
fi

if [ $smp_flags ]; then
	echo "PARALLEL BUILD FLAG SET: $smp_flags"
	echo
fi

jam $SMP -f ../../jam/Jambase $1 $2 $3 $4 $5 $6
