.TH ASTYLE 1 "April 21, 2007" ascend "User's Manual"
.SH NAME
ascend \- A modelling environment for solving equations

.SH SYNOPSIS
.B ascend
[\fIOPTIONS\fR] \fIfilename.a4c\fR

.SH DESCRIPTION
\fBASCEND\fR (or \fBascend\fR) is modelling program that allows you
to solve systems of equations. You write model files (*.a4c) that describe
your system of equations, then you load them into the ASCEND GUI and examine
and solve your equations. For more information see the ASCEND wiki at

http://ascendwiki.cheme.cmu.edu/

