Import('env')
import platform

testsrcs = ['#test/'+i for i in Split("""
  assertimpl.c
  printutil.c
  redirectStdStreams.c
""")]

basesrcs = ['test_ascend_base.c']

srcs = []
for dir in ['general','utilities','solver','linear']:
	srcs += env['TESTSRCS_'+dir.upper()]

cpppath = ['#test','#base/generic']
if env.has_key('CUNIT_CPPPATH'):
	cpppath.append(env['CUNIT_CPPPATH'])

libpath = ['#', '#test', '#base/generic/test']
if env.has_key('CUNIT_LIBPATH'):
	libpath.append(env['CUNIT_LIBPATH'])
	#print "CUNIT_LIBPATH ---> ",libpath

cppdefines = []
if env.has_key('CPPDEFINES'):
	cppdefines += env.get('CPPDEFINES')
cppdefines += ['-DASC_SHARED']

libs = ['ascend','m','cunit']
if platform.system()!="Windows":
	libs += ['dl']

objs = []
for src in srcs+testsrcs:
	objs += env.SharedObject(src
		, CPPPATH = cpppath
	)

objs += env.SharedObject('test_ascend_base.c'
		, CPPPATH = cpppath
	)

#print "OBJS = "
#for o in objs:
#	print o

env.SharedLibrary('asctestsuite',objs
	, CPPPATH = cpppath
	, LIBS = libs
	, LIBPATH = libpath
	, CPPDEFINES = cppdefines
)

env.Program('test',['test.c']
	, CPPPATH = cpppath
	, LIBS = ['ascend','cunit','asctestsuite']
	, LIBPATH = libpath
)
