Import('env')

testsrcs = ['#test/'+i for i in Split("""
  assertimpl.c
  printutil.c
  redirectStdStreams.c
""")]

basesrcs = ['test_ascend_base.c']

srcs = []
for dir in ['general','utilities','solver']:
	srcs += ['#base/generic/'+dir+'/test/'+i for i in env['TESTSRCS_'+dir.upper()]]

env.Program('test',srcs+basesrcs
	, CPPPATH = [
		'#test'
		, '#base/generic'
		, env['CUNIT_CPPPATH']
	  ]
	, LIBS = ['ascutilities','ascgeneral','ascsolver','asccompiler','ascpackages','asctest','m','cunit','dl']
	, LIBPATH = ['#base/generic/utilities', '#base/generic/general', '#base/generic/solver', '#base/generic/compiler', '#base/generic/packages', '#test', env['CUNIT_LIBPATH']]
)
