Import('libascend_env')

csrcs = Split("""
	analyze.c block.c
	bnd.c bndman.c calc.c cond_config.c
	conditional.c discrete.c
	diffvars.c
	jacobian.c
	graph.c
	logrel.c logrelman.c model_reorder.c
	rel.c relman.c
	slv.c
	slv_common.c
	slv_param.c
	slv_stdcalls.c system.c var.c
""")

solver_env = libascend_env.Copy()

for i in libascend_env.get('WITH_SOLVERS'):
    solver_env.Append(CPPDEFINES=["STATIC_"+i])

defs = []
objs = []

for c in csrcs:
	objs += solver_env.SharedObject(c)

#--------------------
# INSTALL

import glob

if libascend_env.get('CAN_INSTALL'):
	installdir = libascend_env['INSTALL_ROOT']+libascend_env['INSTALL_INCLUDE']+'/system'

	headers = glob.glob("*.h")
	libascend_env.InstallHeader(installdir,headers)

Return('objs')

# vim: set syntax=python:

