Import('env')

objs = []

sundials_env = solver_env.Copy()

if env.get('WITH_MMIO'):
	sundials_env.Append(CPPPATH=["#/mmio"])

if env.get('SUNDIALS_CPPPATH'):
	sundials_env.Append(CPPPATH=[env.get('SUNDIALS_CPPPATH')])

if env.get('SUNDIALS_CPPPATH_EXTRA'):
	sundials_env.AppendUnique(
		CPPPATH=env.get('SUNDIALS_CPPPATH_EXTRA')
	)

sundials_env.Append(
	CPPDEFINES=[
		('SUNDIALS_VERSION_MAJOR',"$SUNDIALS_VERSION_MAJOR")
		,('SUNDIALS_VERSION_MINOR',"$SUNDIALS_VERSION_MINOR")
	]
)

sundials_env.Append(
	LIBPATH=[solver_env.get('SUNDIALS_LIBPATH')]
	, LIBS=[solver_env.get('SUNDIALS_LIBS')]
)

idasrcs = ['ida.c','idalinear.c', 'idaanalyse.c']
for s in idasrcs:
	objs += sundials_env.SharedObject(s)

libida = sundials_env.SharedLibrary("ida",objs)

env['extfns'] += libda

if env.get('CAN_INSTALL'):
	dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
	env.InstallShared(dir,libida)

# vim: set syntax=python:
