Import('env')
import subprocess, shutil, pathlib

highs_test_text = """
#include <interfaces/highs_c_api.h>
int main(void){
	void *h = Highs_create();
	if(h)Highs_destroy(h);
	return 0;
}
"""

def CheckHIGHS(context):
	context.Message('Checking for HiGHS for A4SQP... ')
	pkg = shutil.which("pkg-config")
	if pkg is None:
		context.Result('no (pkg-config not found)')
		return False
	try:
		subprocess.run([pkg,"--exists","highs"],stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=True)
	except Exception:
		context.Result('no (pkg-config --exists highs failed)')
		return False

	context.env.ParseConfig(str(pathlib.Path(pkg))+' --cflags --libs highs')
	is_ok = context.TryLink(highs_test_text,".c")
	if is_ok:
		context.Result(True)
	else:
		context.Result('no (failed to link)')
	return is_ok

if env.get('WITH_A4SQP'):
	if not env.get('WITH_HIGHS'):
		env.set_optional('a4sqp',active=False,reason='requires WITH_HIGHS')
		print('Skipping... A4SQP solver requires HiGHS.')
	else:
		solver_env = env.Clone()
		if env['HIGHS_PREFIX'] not in ['/usr']:
			for subdir in ("lib/pkgconfig","lib64/pkgconfig"):
				solver_env.AppendENVPath('PKG_CONFIG_PATH',env.subst(f"$HIGHS_PREFIX/{subdir}"))

		conf = solver_env.Configure(custom_tests={'CheckHIGHS':CheckHIGHS})
		if not conf.CheckHIGHS():
			conf.env['WITH_A4SQP'] = False
		solver_env = conf.Finish()

		env.set_optional('a4sqp',active=solver_env['WITH_A4SQP'],reason='HiGHS not found')
		if not solver_env['WITH_A4SQP']:
			print('Skipping... A4SQP solver requires HiGHS.')
		else:
			solver_env.Append(LIBS=['ascend'],LIBPATH=['#'])
			lib = solver_env.SharedLibrary('a4sqp',[
				'a4sqp.c',
				'a4sqp_ascend.c',
				'a4sqp_c.c',
				'a4sqp_core.c',
				'a4sqp_diag.c',
				'a4sqp_hessian.c',
				'a4sqp_params.c',
				'a4sqp_qp_highs.c',
				'a4sqp_scale.c',
				'a4sqp_trust.c',
				'a4sqp_view.c',
				'a4sqp_view_ascend.c'
			],
				SHLIBSUFFIX = env['EXTLIB_SUFFIX'],
				SHLIBPREFIX = env['EXTLIB_PREFIX']
			)
			env.Depends(lib,env['libascend'])
			env['extfns'] += [lib]
			if env.get('CAN_INSTALL'):
				dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
				env.InstallShared(dir,lib)

# vim: set syntax=python:
