#!/usr/bin/env python
Import('env')

if env.get('WITH_RADAU5'):

	srcs = Split("radau5 decsol.f dc_decsol.f")

	radau5obj = env.SharedObject(srcs)

	lib = env.SharedLibrary("radau5",["asc_radau5.c",radau5obj]
		,LIBS = ['ascend']
		,LIBPATH = ['#']
		,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
		,SHLIBPREFIX = env['EXTLIB_PREFIX']		
	)

	env.Depends(lib,env['libascend'])

	env['extfns'] += lib

	if env.get('CAN_INSTALL'):
		dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
		env.InstallShared(dir,lib)

# vim: set syntax=python:
