Import('libascend_env')

csrcs = Split("""
	incidence.c
	slv_interface.c
	mps.c
	slv2.c slv3.c slv6.c slv7.c
	slv8.c slv9.c slv9a.c slvDOF.c 
	
""")

solver_env = libascend_env.Copy()

defs = []
for i in libascend_env.get('WITH_SOLVERS'):
	solver_env.Append(CPPDEFINES=["STATIC_"+i])

objs = []

if solver_env.get('WITH_CONOPT'):
	solver_env.AppendUnique(CPPPATH=[solver_env.get('CONOPT_CPPPATH')])

	if solver_env.get('LINKED_CONOPT'):
		libascend_env.AppendUnique(
			LIBPATH=[solver_env.get('CONOPT_LIBPATH')]
			, LIBS=[solver_env.get('CONOPT_LIB')]
		)

	objs += solver_env.SharedObject('conopt.c')
#	print "BUILDING CONOPT.OS"

for c in csrcs:
	objs += solver_env.SharedObject(c)

#--------------------
# INSTALL

import glob

if libascend_env.get('CAN_INSTALL'):
	installdir = libascend_env['INSTALL_ROOT']+libascend_env['INSTALL_INCLUDE']+'/solver'

	headers = glob.glob("*.h")
	libascend_env.InstallHeader(installdir,headers)

Return('objs')

# vim: set syntax=python:

