Import('env')

if env.get('WITH_SLSQP'):
	if not env.get('HAVE_NLOPT'):
		env.set_optional('slsqp',active=False,reason='requires NLopt')
		print('Skipping... SLSQP solver requires NLopt.')
	else:
		solver_env = env.Clone()
		solver_env.AppendUnique(
			CPPPATH = env.get('NLOPT_CPPPATH',[]),
			LIBPATH = env.get('NLOPT_LIBPATH',[]) + ['#'],
			LIBS = env.get('NLOPT_LIBS',[]) + ['ascend']
		)
		lib = solver_env.SharedLibrary('slsqp',['asc_slsqp.c'],
			SHLIBSUFFIX = env['EXTLIB_SUFFIX'],
			SHLIBPREFIX = env['EXTLIB_PREFIX']
		)
		env.Depends(lib,env['libascend'])
		env['extfns'] += [lib]
		if env.get('CAN_INSTALL'):
			dir = Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS"))
			env.InstallShared(dir,lib)

# vim: set syntax=python:
