Import('env')
extfn_env = env.Copy()

srcs = Split("""
	extfntest.c
""")

extfn_env.Append(LIBS=['ascend'])

targets = []
targets.append( extfn_env.SharedLibrary("extfntest",srcs) )

# To run the test
# type
#
# ASCENDLIBRARY=../../../models LD_LIBRARY_PATH=../../.. PYTHONPATH=../../../pygtk python extfntest.py

# Return the targs
Return('targets')
