import os
env = Environment(ENV=os.environ)

srcs = Split("""
	extfntest.c
""")

env.SharedLibrary("extfntest",srcs
	, CPPPATH=['../../../base/generic']
	, LIBPREFIX=''
)

# To run the test
# type
#
# PYTHONPATH=../../../pygtk/interface ./extfntest.py

