Import('env')

liblrslv = [env.SharedLibrary("lrslv",["slv9a.c"]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
)]

env['extfns'] += liblrslv

env.Depends(liblrslv,env['libascend'])


if env.get('CAN_INSTALL'):
	env.InstallShared(Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS")),liblrslv)

# vim: set syntax=python:

