Import('env')

# To run the test, type
#     ascend johnpye/conopt/conopt.a4c

solver_env = env.Copy()

if solver_env.get('WITH_CONOPT'):
	solver_env.AppendUnique(CPPPATH=[solver_env.get('CONOPT_CPPPATH')])

libconopt = [solver_env.SharedLibrary("conopt",["asc_conopt.c"]
	,LIBS = ['ascend']
	,LIBPATH = ['#']
)]

env.Depends(libconopt,env['libascend'])

env['extfns'] += libconopt

if env.get('CAN_INSTALL'):
	env.InstallShared(Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS")),libconopt)

# vim: set syntax=python:

