Import('env')

# To run the test, type
#     ascend johnpye/conopt/conopt.a4c

if env.get('WITH_CONOPT'):

	solver_env = env.Copy()

	solver_env.AppendUnique(CPPPATH=[solver_env.get('CONOPT_CPPPATH')])

	lib = solver_env.SharedLibrary("conopt",["asc_conopt.c"]
		,LIBS = ['ascend']
		,LIBPATH = ['#']
		,SHLIBSUFFIX = env['EXTLIB_SUFFIX']
		,SHLIBPREFIX = env['EXTLIB_PREFIX']
	)

	env.Depends(lib,env['libascend'])

	env['extfns'] += [lib]

	if env.get('CAN_INSTALL'):
		env.InstallShared(Dir(env.subst("$INSTALL_ROOT$INSTALL_SOLVERS")),lib)

# vim: set syntax=python:

